const attractionMusic = {
    "Gyeongbokgung Palace": { title: "Life Goes On", artist: "BTS", spotifyId: "4cOdK2LcKz1VNyLbV2FzNL" },
    "Changdeokgung": { title: "Boy With Luv", artist: "BTS ft. Halsey", spotifyId: "5KawlOMHjWeUjQtnuRs22c" },
    "Changgyeonggung": { title: "Spring Day", artist: "BTS", spotifyId: "0xqKIyA5LPLjpxNS7Q4kzC" },
    "Deoksugung": { title: "Butter", artist: "BTS", spotifyId: "21ySn6MagjolSvYG5OGsEe" },
    "Gyeonghuigung": { title: "FAKE LOVE", artist: "BTS", spotifyId: "4VdAEYpTYIs9wroAlI2Xji" },
    "N Seoul Tower": { title: "ON", artist: "BTS", spotifyId: "38zsOOcu31XbbYj9BIPUF1" },
    "Bukchon Hanok Village": { title: "DDU-DU DDU-DU", artist: "BLACKPINK", spotifyId: "4lT0Fk7jEUpZmMxvLMPgEJ" },
    "L7 Myeongdong": { title: "Kill This Love", artist: "BLACKPINK", spotifyId: "2OR4iNGByRYpKoowQKSx1b" },
    "Insadong": { title: "How You Like That", artist: "BLACKPINK", spotifyId: "4SpkVvaRRg8hPpK1YTCvtj" },
    "Dongdaemun Design Plaza": { title: "Lilac", artist: "IU", spotifyId: "5xrtzzzikpG3BLbo4q1Yul" },
    "Lotte Hotel Seoul": { title: "IDOL", artist: "BTS", spotifyId: "6e2JJ9KNxMYA3WbhVnrNVm" },
    "Cheonggyecheon Stream Fashion Plaza": { title: "Blueming", artist: "IU", spotifyId: "7bTHYUyrdB0N87WFHCNhb0" },
    "The War Memorial of Korea": { title: "Love Shot", artist: "EXO", spotifyId: "0ZgMmVQ0uoOJk67R0qcrWD" },
    "National Museum of Korea": { title: "Palette", artist: "IU ft. G-Dragon", spotifyId: "4ISCLU2SUO5sOGI7aL3i0p" },
    "Jogyesa": { title: "Permission to Dance", artist: "BTS", spotifyId: "24b7BLIxDT1X8MojJRfl28" },
    "Hongdae District": { title: "Lovesick Girls", artist: "BLACKPINK", spotifyId: "6FOWmKzjLtQdPjtT1e1aSB" },
    "Yeouido Park": { title: "Black Swan", artist: "BTS", spotifyId: "5a1iz510sv2W9Dt1MvFd5R" },
    "Ichon Hangang Park": { title: "DNA", artist: "BTS", spotifyId: "5WTxpKaVPvmVciSZMOTQ2U" },
    "Haeundae Beach": { title: "Pink Venom", artist: "BLACKPINK", spotifyId: "5zwwW9Oq4MqbOdoXwbnenC" },
    "Gamcheon Culture Village info": { title: "Mic Drop", artist: "BTS", spotifyId: "3zT7Vy2hYUP8SL7s3zX8JV" },
    "Haedong Yonggungsa Temple": { title: "STAY", artist: "BLACKPINK", spotifyId: "3HqSLMAZ3g3d5poNaI7GOU" },
    "Jagalchi Fish Market": { title: "Blood Sweat & Tears", artist: "BTS", spotifyId: "3J5qqBTPUmUkS9WDlw3QKC" },
    "Gwangalli Beach": { title: "Celebrity", artist: "IU", spotifyId: "6LUwS4lWnQkkKluRcfGVjL" },
    "Beomeosa": { title: "Fire", artist: "BTS", spotifyId: "3KPzABzWIzdVsv8hPANMlp" },
    "Busan Tower": { title: "Psycho", artist: "Red Velvet", spotifyId: "6z9ePrQELkCQMDuNQ0DDbv" },
    "BIFF Square": { title: "Monster", artist: "EXO", spotifyId: "2lhmGZqD8DmLyWMjiPdvkT" },
    "Taejongdae Resort Park": { title: "Growl", artist: "EXO", spotifyId: "2j2kPRN5bqfCh2LKcxFO9a" },
    "Songdo Beach": { title: "Cheer Up", artist: "TWICE", spotifyId: "2ohXHa1F3RzXoxs4UXq7mY" },
    "Seongsan ilchulbong": { title: "Dynamite", artist: "BTS", spotifyId: "0t1kP63rueHleOhQkYSXFY" },
    "Hallasan Eorimok": { title: "Boy With Luv", artist: "BTS ft. Halsey", spotifyId: "5KawlOMHjWeUjQtnuRs22c" },
    "Manjanggul Lava Tubes": { title: "Spring Day", artist: "BTS", spotifyId: "0xqKIyA5LPLjpxNS7Q4kzC" },
    "Cheonjiyeon Waterfall": { title: "Butter", artist: "BTS", spotifyId: "21ySn6MagjolSvYG5OGsEe" },
    "Jeongbang Waterfall": { title: "FAKE LOVE", artist: "BTS", spotifyId: "4VdAEYpTYIs9wroAlI2Xji" },
    "Teddy Bear Museum": { title: "Gangnam Style", artist: "PSY", spotifyId: "03UrZgTINDqvnUMbbIMhql" },
    "Jeju Folk Village Museum": { title: "DDU-DU DDU-DU", artist: "BLACKPINK", spotifyId: "4lT0Fk7jEUpZmMxvLMPgEJ" },
    "Udo Island": { title: "Kill This Love", artist: "BLACKPINK", spotifyId: "2OR4iNGByRYpKoowQKSx1b" },
    "Seopjikoji": { title: "How You Like That", artist: "BLACKPINK", spotifyId: "4SpkVvaRRg8hPpK1YTCvtj" },
    "Senso-ji Temple": { title: "Shinzou wo Sasageyo!", artist: "Linked Horizon", spotifyId: "0Rm8xvSbgT6fLX8RQy4GTK" },
    "Tokyo Tower": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "Tokyo Skytree": { title: "Lemon", artist: "Kenshi Yonezu", spotifyId: "0LYBX4M0D0G2yhKCQS8arl" },
    "Meiji Jingu Shrine": { title: "Pretender", artist: "Official HIGE DANdism", spotifyId: "6HCN0fFtkWPzrBuaBDHBwP" },
    "Shibuya Crossing": { title: "Lemon", artist: "Kenshi Yonezu", spotifyId: "0LYBX4M0D0G2yhKCQS8arl" },
    "Imperial Palace": { title: "Homura", artist: "LiSA", spotifyId: "2DGrA1I2Bv9zFNTXo3vz99" },
    "Ueno Park": { title: "Koi", artist: "Gen Hoshino", spotifyId: "6q5CnhXJ0k6HVXQ0KKR8gI" },
    "Akihabara": { title: "A Cruel Angel's Thesis", artist: "Yoko Takahashi", spotifyId: "2HvBuSGlpYx7dKlBCxe7t4" },
    "Shinjuku Gyoen": { title: "KICK BACK", artist: "Kenshi Yonezu", spotifyId: "5qqabIl2vWzo9ApSC317sa" },
    "Harajuku Station": { title: "Idol", artist: "YOASOBI", spotifyId: "1xBdX8k9Fqfm1W1xtxhv5p" },
    "銀座アスター 新宿賓館": { title: "Racing Into The Night", artist: "YOASOBI", spotifyId: "1s2WL5SeSrT2bJ9mSFJfMn" },
    "ASAKUSA": { title: "Sparkle", artist: "RADWIMPS", spotifyId: "7wNH5yL0RJ5Iw2NvvZvLVW" },
    "Tokyo DisneySea": { title: "Zenzenzense", artist: "RADWIMPS", spotifyId: "5yWkWJz7GvlPz7x4cPGZ0u" },
    "teamLab Borderless": { title: "Unravel", artist: "TK from Ling Tosite Sigure", spotifyId: "5aX7qAGfQfbLn8gI7cCKo8" },
    "Osaka Castle": { title: "First Love", artist: "Hikaru Utada", spotifyId: "3OQCfxSE0oOqQKVMXxL9DE" },
    "Dotonbori": { title: "Plastic Love", artist: "Mariya Takeuchi", spotifyId: "4AwAexBVNEddZYvw3n3c79" },
    "Universal Studios Japan": { title: "Homura", artist: "LiSA", spotifyId: "2DGrA1I2Bv9zFNTXo3vz99" },
    "Shitennoji Temple Kindo": { title: "Koi", artist: "Gen Hoshino", spotifyId: "6q5CnhXJ0k6HVXQ0KKR8gI" },
    "Osaka Aquarium Kaiyukan": { title: "A Cruel Angel's Thesis", artist: "Yoko Takahashi", spotifyId: "2HvBuSGlpYx7dKlBCxe7t4" },
    "Sumiyoshi Taisha": { title: "KICK BACK", artist: "Kenshi Yonezu", spotifyId: "5qqabIl2vWzo9ApSC317sa" },
    "Shinsekai": { title: "Idol", artist: "YOASOBI", spotifyId: "1xBdX8k9Fqfm1W1xtxhv5p" },
    "Umeda Sky Building": { title: "Racing Into The Night", artist: "YOASOBI", spotifyId: "1s2WL5SeSrT2bJ9mSFJfMn" },
    "Kuromon Market": { title: "Sparkle", artist: "RADWIMPS", spotifyId: "7wNH5yL0RJ5Iw2NvvZvLVW" },
    "Fukuoka Tower": { title: "Zenzenzense", artist: "RADWIMPS", spotifyId: "5yWkWJz7GvlPz7x4cPGZ0u" },
    "Dazaifu Tenmangu Shrine": { title: "Unravel", artist: "TK from Ling Tosite Sigure", spotifyId: "5aX7qAGfQfbLn8gI7cCKo8" },
    "Ohori Park": { title: "Shinzou wo Sasageyo!", artist: "Linked Horizon", spotifyId: "0Rm8xvSbgT6fLX8RQy4GTK" },
    "Canal City Hakata": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "Fukuoka Castle Ruins": { title: "Pretender", artist: "Official HIGE DANdism", spotifyId: "6HCN0fFtkWPzrBuaBDHBwP" },
    "Kushida Shrine": { title: "Lemon", artist: "Kenshi Yonezu", spotifyId: "0LYBX4M0D0G2yhKCQS8arl" },
    "Forbidden City": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Great Wall Of China": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Temple of Heaven": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Summer Palace": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Tian\'anmen Square": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Beihai Park": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Ming Tombs": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "798 Art Zone": { title: "Thinking Out Loud", artist: "Ed Sheeran", spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    "Yonghegong Lama Temple": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Jingshan Park": { title: "Lean On", artist: "Major Lazer", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "The Bund": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Oriental Pearl Tower": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Yu Garden": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Shanghai Tower": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Nanjing Road Pedestrian Street": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Shanghai Museum": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Jade Buddha Temple": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Former French Concession": { title: "Thinking Out Loud", artist: "Ed Sheeran", spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    "Zhujiajiao Ancient Town": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Shanghai Disneyland": { title: "Lean On", artist: "Major Lazer", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "Canton Tower": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Chen Clan Ancestral Hall": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Shamian Island": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Baiyun Mountain": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Great Buddha Temple": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Guangdong Museum": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Victoria Peak": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Tian Tan Buddha": { title: "Thinking Out Loud", artist: "Ed Sheeran", spotifyId: "34gCuhDGsG4bRPIf9bb02f" },
    "Hong Kong Disneyland": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Ocean Park Hong Kong": { title: "Lean On", artist: "Major Lazer", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "Victoria Harbour": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Wong Tai Sin Temple": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Star Ferry": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Temple Street Night Market": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Ngong Ping 360 Tung Chung Station": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Man Mo Temple": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Taipei 101": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "National Palace Museum": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Chiang Kai-Shek Memorial Hall": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Longshan Temple": { title: "Counting Stars", artist: "OneRepublic", spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    "Shilin Night Market": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Jiufen Old Street": { title: "Hello", artist: "Adele", spotifyId: "4sPmO7WMQUAf45kwMOtONw" },
    "Elephant Mountain": { title: "Sugar", artist: "Maroon 5", spotifyId: "2iuZJX9X9P0GKaE93xcPjk" },
    "Beitou Hot Spring Museum": { title: "Photograph", artist: "Ed Sheeran", spotifyId: "1HNkqx9Ahdgi1Ixy2xkKkL" },
    "Maokong Gondola Line": { title: "Let Her Go", artist: "Passenger", spotifyId: "2ggKAly9Ys99cGZ4fxRfKF" },
    "Sun Yat-sen Memorial Hall Loop": { title: "Havana", artist: "Camila Cabello", spotifyId: "1rfofaqEpACxVEHIZBJe6W" },
    "Wat Arun Prang": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Wat Pho": { title: "MONEY", artist: "LISA", spotifyId: "7hxHWCCAIIxFLCzvDgnQHX" },
    "Chatuchak Weekend Market": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Khao San Road": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "The Jim Thompson House": { title: "Faded", artist: "Alan Walker", spotifyId: "7gHs73wELdeycvS48JfIos" },
    "Wat Saket": { title: "Something Just Like This", artist: "Coldplay & The Chainsmokers", spotifyId: "6RUKPb4LETWmmr3iAEQktW" },
    "Lumphini Park": { title: "Rockabye", artist: "Clean Bandit", spotifyId: "5knuzwU65gOF0RJtuWCqx8" },
    "Erawan Shrine": { title: "Alone", artist: "Alan Walker", spotifyId: "0JiVRyTJcJnmlwMU1Qnuj1" },
    "Chinatown Bangkok": { title: "Titanium", artist: "David Guetta ft. Sia", spotifyId: "0lHAMNU8RGiIObScrsRgmP" },
    "Patong Beach": { title: "LALISA", artist: "LISA", spotifyId: "1DP7PGSwI13pvHAIKvluhd" },
    "Blu Monkey Phuket Phangnga Road": { title: "MONEY", artist: "LISA", spotifyId: "7hxHWCCAIIxFLCzvDgnQHX" },
    "Kata Beach": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Phuket Old Town Hostel": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Phi Phi Islands": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Phang Nga Bay": { title: "Faded", artist: "Alan Walker", spotifyId: "7gHs73wELdeycvS48JfIos" },
    "Wat Chaithararam": { title: "Something Just Like This", artist: "Coldplay & The Chainsmokers", spotifyId: "6RUKPb4LETWmmr3iAEQktW" },
    "Wat Phrathat Doi Suthep": { title: "Rockabye", artist: "Clean Bandit", spotifyId: "5knuzwU65gOF0RJtuWCqx8" },
    "Chiang Mai Night Bazaar": { title: "Alone", artist: "Alan Walker", spotifyId: "0JiVRyTJcJnmlwMU1Qnuj1" },
    "Wat Phra Singh Waramahavihan": { title: "Titanium", artist: "David Guetta ft. Sia", spotifyId: "0lHAMNU8RGiIObScrsRgmP" },
    "Elephant Nature Park": { title: "LALISA", artist: "LISA", spotifyId: "1DP7PGSwI13pvHAIKvluhd" },
    "Old City Chiang Mai": { title: "MONEY", artist: "LISA", spotifyId: "7hxHWCCAIIxFLCzvDgnQHX" },
    "doi inthanon": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Marina Bay Sands": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Gardens by the Bay": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Sentosa Island": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Singapore Zoo": { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", spotifyId: "0WsA2iHPVvxkg4Nsv769vx" },
    "Merlion Park": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Orchard Road": { title: "Shut Up and Dance", artist: "WALK THE MOON", spotifyId: "4kbj5MwxO1bq9wjT5g9HaA" },
    "Hostel, Chinatown, Singapore": { title: "Shake It Off", artist: "Taylor Swift", spotifyId: "0cqRj7pUJDkTCEsJkx8snD" },
    "little india singapore": { title: "24K Magic", artist: "Bruno Mars", spotifyId: "6b8Be6ljOzmkOmFslEb23P" },
    "Universal Studios Singapore": { title: "Don't Start Now", artist: "Dua Lipa", spotifyId: "3PfIrDoz19wz7qK7tYeu62" },
    "Clarke Quay": { title: "Levitating", artist: "Dua Lipa", spotifyId: "463CkQjx2Zk1yXoBuierM9" },
    "Notre Dame Cathedral": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Ben Thanh Market": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Địa đạo Củ Chi": { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", spotifyId: "2JzZzZUQj3Qff7wapcbKjc" },
    "War Remnants Museum": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Independence Palace": { title: "Perfect", artist: "Ed Sheeran", spotifyId: "0tgVpDi06FyKpA1z0VMD4v" },
    "Saigon Central Post Office": { title: "Something Just Like This", artist: "Coldplay", spotifyId: "6RUKPb4LETWmmr3iAEQktW" },
    "Jade Emperor Pagoda": { title: "Faded", artist: "Alan Walker", spotifyId: "7gHs73wELdeycvS48JfIos" },
    "Hoàn Kiếm Lake": { title: "Let Me Love You", artist: "DJ Snake", spotifyId: "0lYBSQXN6rCTvUZvg9S0lU" },
    "Ho Chi Minh Mausoleum": { title: "Cold Water", artist: "Major Lazer", spotifyId: "5a5OisiGGlxhQcuB98ZXlk" },
    "Temple of Literature": { title: "Cheap Thrills", artist: "Sia", spotifyId: "27SdWb2rFzO6GWiYDBTD9j" },
    "Old Quarter Hotel Hanoi": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Ha Long Bay": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Chùa Một Cột": { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", spotifyId: "2JzZzZUQj3Qff7wapcbKjc" },
    "Tran Quoc Pagoda": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Big Ben": { title: "London Calling", artist: "The Clash", spotifyId: "6vk0xhXh8cKMLjQfnMD0uH" },
    "Tower of London": { title: "Bohemian Rhapsody", artist: "Queen", spotifyId: "4u7EnebtmKWzUH433cf5Qv" },
    "British Museum": { title: "Wonderwall", artist: "Oasis", spotifyId: "1qPbGZqppFwLwcBC1JQ6Vr" },
    "Buckingham Palace": { title: "Viva La Vida", artist: "Coldplay", spotifyId: "1mea3bSkSGXuIRvnydlB5b" },
    "The London Eye": { title: "Don't Look Back in Anger", artist: "Oasis", spotifyId: "5r2wSt27gCy1HHDTqBImsz" },
    "Tower Bridge": { title: "Yellow", artist: "Coldplay", spotifyId: "3AJwUDP919kvQ9QcozQPxg" },
    "Westminster Abbey": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "St Paul\'s Cathedral": { title: "Someone Like You", artist: "Adele", spotifyId: "1zwMYTA5nlNjZxYrvBB2pV" },
    "Hyde Park": { title: "Rolling in the Deep", artist: "Adele", spotifyId: "4OSBTFsWvxALJ3GzJwvJQx" },
    "Trafalgar Square": { title: "A Day In The Life", artist: "The Beatles", spotifyId: "0hKRSZhUGEhKU6aNSPBACZ" },
    "Piccadilly Circus": { title: "Hey Jude", artist: "The Beatles", spotifyId: "0aym2LBJBk9DAYuHHutrIl" },
    "The Shard": { title: "We Will Rock You", artist: "Queen", spotifyId: "54flyrjcdnQdco2300avMJ" },
    "Natural History Museum": { title: "Don't Stop Me Now", artist: "Queen", spotifyId: "7hQJA50XrCWABAu5v6QZ4i" },
    "Edinburgh Castle": { title: "Fix You", artist: "Coldplay", spotifyId: "7LVHVU3tWfcxj5aiPFEW4Q" },
    "The Royal Mile": { title: "The Scientist", artist: "Coldplay", spotifyId: "75JFxkI2RXiU7L9VXzMkle" },
    "Arthur\'s Seat": { title: "Clocks", artist: "Coldplay", spotifyId: "0BCPKOYdS2jbQ8iyB56Crc" },
    "Palace of Holyroodhouse": { title: "Mr. Brightside", artist: "The Killers", spotifyId: "3n3Ppam7vgaVa1iaRUc9Lp" },
    "National Museum of Scotland": { title: "Watermelon Sugar", artist: "Harry Styles", spotifyId: "6UelLqGlWMcVH1E5c4H7lY" },
    "Calton Hill": { title: "As It Was", artist: "Harry Styles", spotifyId: "4LRPiXqCikLlN15c3yImP7" },
    "Eiffel Tower": { title: "La Vie en Rose", artist: "Edith Piaf", spotifyId: "6KBYk8OFtod7brGuZ3Y67c" },
    "Louvre Museum": { title: "Non, Je Ne Regrette Rien", artist: "Edith Piaf", spotifyId: "7qAV0Plr1I0lBx3r6nkZzL" },
    "Cathedral of Notre-Dame de Paris": { title: "Sous le ciel de Paris", artist: "Edith Piaf", spotifyId: "3tZP8lOZt6xCpnJjNpzRMI" },
    "Arc de Triomphe": { title: "Alors On Danse", artist: "Stromae", spotifyId: "10FLjwfpbxLmW8c25Xyc2N" },
    "Champs-Élysées": { title: "Chandelier", artist: "Sia", spotifyId: "4VrWlk8IQxevMvERoX08iC" },
    "Sacré-Cœur Basilica": { title: "Lady Marmalade", artist: "Christina Aguilera", spotifyId: "0pXy33r3DjVMvlmYFHDZiS" },
    "Orsay Museum": { title: "Get Lucky", artist: "Daft Punk", spotifyId: "2Foc5Q5nqNiosCNqttzHof" },
    "Palace of Versailles": { title: "One More Time", artist: "Daft Punk", spotifyId: "0DiWol3AO6WpXZgp0goxAV" },
    "Moulin Rouge": { title: "Around the World", artist: "Daft Punk", spotifyId: "1pKYYY0dkg23sQQXi0Q5zN" },
    "Montmartre": { title: "Papaoutai", artist: "Stromae", spotifyId: "2jnJfllDqH4YLlC4DxMZFt" },
    "Luxembourg Gardens": { title: "Je Veux", artist: "Zaz", spotifyId: "6TGd66r0nlPaYm5FJqR4mT" },
    "Sainte-Chapelle": { title: "Formidable", artist: "Stromae", spotifyId: "0gTXcNLtJlYIEinv9Wrjht" },
    "Promenade des Anglais": { title: "La Vie en Rose", artist: "Edith Piaf", spotifyId: "6KBYk8OFtod7brGuZ3Y67c" },
    "ibis Styles Nice Centre Gare": { title: "Non, Je Ne Regrette Rien", artist: "Edith Piaf", spotifyId: "7qAV0Plr1I0lBx3r6nkZzL" },
    "Castle Hill": { title: "Sous le ciel de Paris", artist: "Edith Piaf", spotifyId: "3tZP8lOZt6xCpnJjNpzRMI" },
    "Muséum d\'Histoire Naturelle de Nice": { title: "Alors On Danse", artist: "Stromae", spotifyId: "10FLjwfpbxLmW8c25Xyc2N" },
    "Musée Marc Chagall": { title: "Chandelier", artist: "Sia", spotifyId: "4VrWlk8IQxevMvERoX08iC" },
    "Colosseum Bar": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "Vatican City": { title: "Con Te Partiro", artist: "Andrea Bocelli", spotifyId: "0VLWREgzN6yy4jSnTzTCgQ" },
    "Trevi Fountain": { title: "That's Amore", artist: "Dean Martin", spotifyId: "0oGQvYRqXYmaxdlLiSJM4d" },
    "Pantheon": { title: "Nessun Dorma", artist: "Luciano Pavarotti", spotifyId: "5WJIqwNDPSGl8YkFDPgVmk" },
    "Roman Forum": { title: "O Sole Mio", artist: "Luciano Pavarotti", spotifyId: "5gVg1nJKxC2e3wt0X1qYJp" },
    "St. Peter\'s Basilica": { title: "La donna e mobile", artist: "Luciano Pavarotti", spotifyId: "5e8xnM5g2hZkW7dJqVp7Rj" },
    "Sistine Chapel": { title: "Felicita", artist: "Al Bano & Romina Power", spotifyId: "0Q0cexH7aLfJZLWHrqBNbR" },
    "Inn At The Spanish Steps": { title: "Gloria", artist: "Umberto Tozzi", spotifyId: "2TqgdoBm8HkWdUT8WjciFB" },
    "Piazza Navona": { title: "Zitti E Buoni", artist: "Maneskin", spotifyId: "3mNpnLFLwaExuW8r2q3T94" },
    "Castle of the Holy Angel": { title: "Beggin'", artist: "Maneskin", spotifyId: "3Wrjm47oTz2sjIgck11l5e" },
    "Villa Borghese": { title: "I Wanna Be Your Slave", artist: "Maneskin", spotifyId: "2Le5Wc9FSPX8T8bXxDKZm3" },
    "Milan Cathedral View": { title: "Coraline", artist: "Maneskin", spotifyId: "1D0MQjCJQlsA1bLXMRLmhC" },
    "Galleria Vittorio Emanuele II": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "Museum of the Last Supper": { title: "Con Te Partiro", artist: "Andrea Bocelli", spotifyId: "0VLWREgzN6yy4jSnTzTCgQ" },
    "Sforza Castle": { title: "That's Amore", artist: "Dean Martin", spotifyId: "0oGQvYRqXYmaxdlLiSJM4d" },
    "La Scala": { title: "Nessun Dorma", artist: "Luciano Pavarotti", spotifyId: "5WJIqwNDPSGl8YkFDPgVmk" },
    "Pinacoteca di Brera": { title: "O Sole Mio", artist: "Luciano Pavarotti", spotifyId: "5gVg1nJKxC2e3wt0X1qYJp" },
    "Porta Nuova Food District": { title: "La donna e mobile", artist: "Luciano Pavarotti", spotifyId: "5e8xnM5g2hZkW7dJqVp7Rj" },
    "Saint Mark\'s Square": { title: "Felicita", artist: "Al Bano & Romina Power", spotifyId: "0Q0cexH7aLfJZLWHrqBNbR" },
    "Rialto Bridge": { title: "Gloria", artist: "Umberto Tozzi", spotifyId: "2TqgdoBm8HkWdUT8WjciFB" },
    "Canal Grande": { title: "Zitti E Buoni", artist: "Maneskin", spotifyId: "3mNpnLFLwaExuW8r2q3T94" },
    "Doge\'s Palace": { title: "Beggin'", artist: "Maneskin", spotifyId: "3Wrjm47oTz2sjIgck11l5e" },
    "St Mark\'s Basilica": { title: "I Wanna Be Your Slave", artist: "Maneskin", spotifyId: "2Le5Wc9FSPX8T8bXxDKZm3" },
    "Burano Island": { title: "Coraline", artist: "Maneskin", spotifyId: "1D0MQjCJQlsA1bLXMRLmhC" },
    "Faro di Murano": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "The St. Regis Florence": { title: "Con Te Partiro", artist: "Andrea Bocelli", spotifyId: "0VLWREgzN6yy4jSnTzTCgQ" },
    "Uffizi Gallery": { title: "That's Amore", artist: "Dean Martin", spotifyId: "0oGQvYRqXYmaxdlLiSJM4d" },
    "Ponte Vecchio": { title: "Nessun Dorma", artist: "Luciano Pavarotti", spotifyId: "5WJIqwNDPSGl8YkFDPgVmk" },
    "Piazzale Michelangelo": { title: "O Sole Mio", artist: "Luciano Pavarotti", spotifyId: "5gVg1nJKxC2e3wt0X1qYJp" },
    "Pitti Palace": { title: "La donna e mobile", artist: "Luciano Pavarotti", spotifyId: "5e8xnM5g2hZkW7dJqVp7Rj" },
    "Gallery of the Academy": { title: "Felicita", artist: "Al Bano & Romina Power", spotifyId: "0Q0cexH7aLfJZLWHrqBNbR" },
    "Royal Palace of Madrid": { title: "Waka Waka", artist: "Shakira", spotifyId: "2Cd9iWfcOpGDHLz6tVA3G4" },
    "Museo Nacional del Prado": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Plaza Mayor": { title: "Bailando", artist: "Enrique Iglesias", spotifyId: "6YYxC3DRTorO8EyXbEfHxe" },
    "Retiro Park": { title: "La Bicicleta", artist: "Shakira & Carlos Vives", spotifyId: "3tpUZS9pXpBxE9WmPMHjWJ" },
    "Puerta del Sol": { title: "Hips Don't Lie", artist: "Shakira", spotifyId: "3ZFTkvIE7kyPt6Nu3PEa7V" },
    "Metro Gran Vía": { title: "Whenever, Wherever", artist: "Shakira", spotifyId: "2lnzGkdtDj5mtlcOW2yRtG" },
    "Reina Sofía Shuttle": { title: "Me Enamore", artist: "Shakira", spotifyId: "5F7TdffWfGgkZOPYwJfLoq" },
    "Santiago Bernabéu Stadium": { title: "Vivir Mi Vida", artist: "Marc Anthony", spotifyId: "3Ua4yQ5W9e5tO2Bi0QCXUo" },
    "The Basilica of the Sagrada Familia": { title: "La Camisa Negra", artist: "Juanes", spotifyId: "4CY0NLXTGYzrtrqyjZOAu2" },
    "Park Güell": { title: "Livin la Vida Loca", artist: "Ricky Martin", spotifyId: "4nAN4FqH4G6mxVXqMGm7H3" },
    "La Rambla": { title: "Waka Waka", artist: "Shakira", spotifyId: "2Cd9iWfcOpGDHLz6tVA3G4" },
    "Casa Batlló": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "La Pedrera": { title: "Bailando", artist: "Enrique Iglesias", spotifyId: "6YYxC3DRTorO8EyXbEfHxe" },
    "Gothic Quarter": { title: "La Bicicleta", artist: "Shakira & Carlos Vives", spotifyId: "3tpUZS9pXpBxE9WmPMHjWJ" },
    "La Boqueria Food Market": { title: "Hips Don't Lie", artist: "Shakira", spotifyId: "3ZFTkvIE7kyPt6Nu3PEa7V" },
    "Camp Nou": { title: "Whenever, Wherever", artist: "Shakira", spotifyId: "2lnzGkdtDj5mtlcOW2yRtG" },
    "Barceloneta Beach": { title: "Me Enamore", artist: "Shakira", spotifyId: "5F7TdffWfGgkZOPYwJfLoq" },
    "Montjuïc Mountain": { title: "Vivir Mi Vida", artist: "Marc Anthony", spotifyId: "3Ua4yQ5W9e5tO2Bi0QCXUo" },
    "Römerberg": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "Frankfurt Cathedral": { title: "Rock Me Amadeus", artist: "Falco", spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    "Palmengarten": { title: "Take on Me", artist: "a-ha", spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    "Main Tower": { title: "The Final Countdown", artist: "Europe", spotifyId: "1JNxNnV1Dqb0NHlPg8X7lI" },
    "Städel Museum": { title: "Blue (Da Ba Dee)", artist: "Eiffel 65", spotifyId: "2sLwT4LXQH3fXBiHFfHvqQ" },
    "Marienplatz": { title: "Sandstorm", artist: "Darude", spotifyId: "6Sy9BUbgFse0n0LPA5lwy5" },
    "Nymphenburg Palace": { title: "Levels", artist: "Avicii", spotifyId: "0xSAI2SQ9vTSLPCCPhTvHV" },
    "English Garden": { title: "Wake Me Up", artist: "Avicii", spotifyId: "0nrRP2bk19rLc0orkWPQk2" },
    "BMW Museum": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "Castle Eigentum GmbH": { title: "Rock Me Amadeus", artist: "Falco", spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    "Cathedral of Our Dear Lady": { title: "Take on Me", artist: "a-ha", spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    "Viktualienmarkt": { title: "The Final Countdown", artist: "Europe", spotifyId: "1JNxNnV1Dqb0NHlPg8X7lI" },
    "Brandenburg gate": { title: "Blue (Da Ba Dee)", artist: "Eiffel 65", spotifyId: "2sLwT4LXQH3fXBiHFfHvqQ" },
    "Berlin Wall Memorial": { title: "Sandstorm", artist: "Darude", spotifyId: "6Sy9BUbgFse0n0LPA5lwy5" },
    "Reichstag building": { title: "Levels", artist: "Avicii", spotifyId: "0xSAI2SQ9vTSLPCCPhTvHV" },
    "Museum Island": { title: "Wake Me Up", artist: "Avicii", spotifyId: "0nrRP2bk19rLc0orkWPQk2" },
    "Checkpoint Charlie": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "Berlin Cathedral": { title: "Rock Me Amadeus", artist: "Falco", spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    "East Side Gallery": { title: "Take on Me", artist: "a-ha", spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    "Alexanderplatz": { title: "The Final Countdown", artist: "Europe", spotifyId: "1JNxNnV1Dqb0NHlPg8X7lI" },
    "Anne Frank House": { title: "Levels", artist: "Avicii", spotifyId: "0xSAI2SQ9vTSLPCCPhTvHV" },
    "Van Gogh Museum": { title: "Wake Me Up", artist: "Avicii", spotifyId: "0nrRP2bk19rLc0orkWPQk2" },
    "Rijksmuseum": { title: "Titanium", artist: "David Guetta ft. Sia", spotifyId: "0lHAMNU8RGiIObScrsRgmP" },
    "Royal Palace of Amsterdam": { title: "Animals", artist: "Martin Garrix", spotifyId: "3Ua4yQ5W9e5tO2Bi0QCXUo" },
    "Dam": { title: "Tsunami", artist: "DVBBS & Borgeous", spotifyId: "5Y5GbWEQM08vRnEtPhz8FD" },
    "Vondelpark": { title: "Lean On", artist: "Major Lazer & DJ Snake", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "De Jordaan": { title: "Scared to Be Lonely", artist: "Martin Garrix", spotifyId: "4hx5wnyVFXdF1P0bK4Bw6g" },
    "Amsterdam Canal Cruises": { title: "In the Name of Love", artist: "Martin Garrix", spotifyId: "5rKL8v23RYXuqnMfR5b8Vh" },
    "Heineken Experience": { title: "Fade", artist: "Alan Walker", spotifyId: "7FG3pN4HHe2zXpM4CRylYR" },
    "Schönbrunn Palace,": { title: "Rock Me Amadeus", artist: "Falco", spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    "St. Stephen\'s Cathedral": { title: "The Blue Danube", artist: "Johann Strauss II", spotifyId: "4oNXgGnumnu5oIkVnMGseb" },
    "Upper Belvedere": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "Hofburg": { title: "Take on Me", artist: "a-ha", spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    "Vienna State Opera": { title: "The Final Countdown", artist: "Europe", spotifyId: "1JNxNnV1Dqb0NHlPg8X7lI" },
    "Wiener Prater": { title: "Vienna", artist: "Billy Joel", spotifyId: "4U45aEWtQhrm8A5mxPaFZ7" },
    "Vienna Museum of Art History": { title: "Waltz No. 2", artist: "Dmitri Shostakovich", spotifyId: "1s2WL5SeSrT2bJ9mSFJfMn" },
    "Charles Bridge": { title: "The Moldau", artist: "Bedrich Smetana", spotifyId: "6k6EPsXkrrZSHAu14UEY1D" },
    "Prague Castle": { title: "Take on Me", artist: "a-ha", spotifyId: "2WfaOiMkCvy7F5fcp2zZ8L" },
    "Old Town Square": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "Prague Astronomical Clock": { title: "The Final Countdown", artist: "Europe", spotifyId: "1JNxNnV1Dqb0NHlPg8X7lI" },
    "St. Vitus Cathedral": { title: "Sandstorm", artist: "Darude", spotifyId: "6Sy9BUbgFse0n0LPA5lwy5" },
    "Wenceslas Square Hotel": { title: "Levels", artist: "Avicii", spotifyId: "0xSAI2SQ9vTSLPCCPhTvHV" },
    "Lennon Wall": { title: "Mr. Brightside", artist: "The Killers", spotifyId: "3n3Ppam7vgaVa1iaRUc9Lp" },
    "Statue of Liberty": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "Empire State Building": { title: "New York, New York", artist: "Frank Sinatra", spotifyId: "4ErGkZiq1njmKDd2MNkwgS" },
    "Central Park Mall": { title: "New York State of Mind", artist: "Billy Joel", spotifyId: "6pz4lFuDJvxMnGJzOKMxWm" },
    "Times Square": { title: "Welcome to New York", artist: "Taylor Swift", spotifyId: "3nqsehvZjJgc2IRECe4uO6" },
    "Brooklyn Bridge": { title: "Brooklyn Baby", artist: "Lana Del Rey", spotifyId: "53DlTPwpjqNaE8iUv5fH8w" },
    "Metropolitan Museum of Art": { title: "Hotel California", artist: "Eagles", spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    "One World Trade Center": { title: "California Gurls", artist: "Katy Perry", spotifyId: "1XkGORuUX2QGOEIL4EbJKm" },
    "Grand Central Terminal": { title: "California Dreamin'", artist: "The Mamas & The Papas", spotifyId: "3VsSyQfF2vfNGp0tbOD0Q6" },
    "Rockefeller Center": { title: "City of Stars", artist: "Ryan Gosling, Emma Stone", spotifyId: "3YRCqOhFifThpSRFJ1VWFM" },
    "401 Broadway": { title: "Viva Las Vegas", artist: "Elvis Presley", spotifyId: "4BMqHoT1TGjEdmFLy2edHn" },
    "Saks Fifth Avenue": { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", spotifyId: "7e89621JPkKaeDSTQ3avtg" },
    "Museum of Modern Art": { title: "Take Me Home, Country Roads", artist: "John Denver", spotifyId: "2bs01VEL73d6IIVFNK4JY3" },
    "Hollywood Sign": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Universal Studios Hollywood": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Santa Monica Pier": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Griffith Observatory": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Hollywood Walk of Fame": { title: "Anti-Hero", artist: "Taylor Swift", spotifyId: "0V3wPSX9ygBnCm8psDIegu" },
    "J. Paul Getty Museum": { title: "Cruel Summer", artist: "Taylor Swift", spotifyId: "1BxfuPKGuaTgP7aM0Bbdwr" },
    "Venice Beach": { title: "Heat Waves", artist: "Glass Animals", spotifyId: "3USxtqRwSYz57Ewm6wWRMp" },
    "Style Beverly Hills": { title: "Sunflower", artist: "Post Malone & Swae Lee", spotifyId: "3KkXRkHbMCARz0aVfEt68P" },
    "Disneyland Park": { title: "Counting Stars", artist: "OneRepublic", spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    "The Grove": { title: "High Hopes", artist: "Panic! At The Disco", spotifyId: "1rqqCSm0Qe4I9rUvWncaom" },
    "Golden Gate Bridge": { title: "Hotline Bling", artist: "Drake", spotifyId: "0wwPcA6wtMf6HUMpIRdeP7" },
    "Alcatraz Island": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Fisherman\'s Wharf": { title: "golden hour", artist: "JVKE", spotifyId: "5odlY52u43F5BjByhxg7wg" },
    "Pier 39": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "Lombard Street": { title: "New York, New York", artist: "Frank Sinatra", spotifyId: "4ErGkZiq1njmKDd2MNkwgS" },
    "Chinatown San Francisco": { title: "New York State of Mind", artist: "Billy Joel", spotifyId: "6pz4lFuDJvxMnGJzOKMxWm" },
    "Powell Street Cable Car Turnaround": { title: "Welcome to New York", artist: "Taylor Swift", spotifyId: "3nqsehvZjJgc2IRECe4uO6" },
    "Golden Gate Park": { title: "Brooklyn Baby", artist: "Lana Del Rey", spotifyId: "53DlTPwpjqNaE8iUv5fH8w" },
    "Palace of Fine Arts": { title: "Hotel California", artist: "Eagles", spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    "The Las Vegas Strip": { title: "California Gurls", artist: "Katy Perry", spotifyId: "1XkGORuUX2QGOEIL4EbJKm" },
    "Fountains of Bellagio": { title: "California Dreamin'", artist: "The Mamas & The Papas", spotifyId: "3VsSyQfF2vfNGp0tbOD0Q6" },
    "Fremont Street Experience": { title: "City of Stars", artist: "Ryan Gosling, Emma Stone", spotifyId: "3YRCqOhFifThpSRFJ1VWFM" },
    "Grand Canyon": { title: "Viva Las Vegas", artist: "Elvis Presley", spotifyId: "4BMqHoT1TGjEdmFLy2edHn" },
    "Hoover Dam": { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", spotifyId: "7e89621JPkKaeDSTQ3avtg" },
    "The Venetian Resort Las Vegas": { title: "Take Me Home, Country Roads", artist: "John Denver", spotifyId: "2bs01VEL73d6IIVFNK4JY3" },
    "High Roller Observation Wheel": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "South Beach": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Wynwood Arts District": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "HistoryMiami Museum": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Wynwood Walls": { title: "Anti-Hero", artist: "Taylor Swift", spotifyId: "0V3wPSX9ygBnCm8psDIegu" },
    "Little Havana": { title: "Cruel Summer", artist: "Taylor Swift", spotifyId: "1BxfuPKGuaTgP7aM0Bbdwr" },
    "Everglades National Park": { title: "Heat Waves", artist: "Glass Animals", spotifyId: "3USxtqRwSYz57Ewm6wWRMp" },
    "Walt Disney World Resort": { title: "Sunflower", artist: "Post Malone & Swae Lee", spotifyId: "3KkXRkHbMCARz0aVfEt68P" },
    "Universal Orlando Resort": { title: "Counting Stars", artist: "OneRepublic", spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    "SeaWorld Orlando": { title: "High Hopes", artist: "Panic! At The Disco", spotifyId: "1rqqCSm0Qe4I9rUvWncaom" },
    "Kennedy Space Center Fcu": { title: "Hotline Bling", artist: "Drake", spotifyId: "0wwPcA6wtMf6HUMpIRdeP7" },
    "Magic Kingdom Park": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Epcot": { title: "golden hour", artist: "JVKE", spotifyId: "5odlY52u43F5BjByhxg7wg" },
    "Lincoln Memorial": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "Washington Monument": { title: "New York, New York", artist: "Frank Sinatra", spotifyId: "4ErGkZiq1njmKDd2MNkwgS" },
    "The White House": { title: "New York State of Mind", artist: "Billy Joel", spotifyId: "6pz4lFuDJvxMnGJzOKMxWm" },
    "United States Capitol": { title: "Welcome to New York", artist: "Taylor Swift", spotifyId: "3nqsehvZjJgc2IRECe4uO6" },
    "National Mall": { title: "Brooklyn Baby", artist: "Lana Del Rey", spotifyId: "53DlTPwpjqNaE8iUv5fH8w" },
    "Smithsonian Institution Building": { title: "Hotel California", artist: "Eagles", spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
    "Thomas Jefferson Memorial": { title: "California Gurls", artist: "Katy Perry", spotifyId: "1XkGORuUX2QGOEIL4EbJKm" },
    "Arlington National Cemetery": { title: "California Dreamin'", artist: "The Mamas & The Papas", spotifyId: "3VsSyQfF2vfNGp0tbOD0Q6" },
    "Sydney Opera House": { title: "Down Under", artist: "Men At Work", spotifyId: "1B8G0Pybu3V0b6xNQ2LLV0" },
    "Sydney Harbour Bridge": { title: "Somebody That I Used to Know", artist: "Gotye", spotifyId: "1qDrWA6lyx8cLECdZE7TV7" },
    "Bondi Beach": { title: "Torn", artist: "Natalie Imbruglia", spotifyId: "3LA4alRauE9xMGhkkwjqzL" },
    "Darling Harbour": { title: "Chandelier", artist: "Sia", spotifyId: "4VrWlk8IQxevMvERoX08iC" },
    "Taronga Zoo": { title: "Cheap Thrills", artist: "Sia", spotifyId: "27SdWb2rFzO6GWiYDBTD9j" },
    "Royal Botanic Garden": { title: "Dance Monkey", artist: "Tones And I", spotifyId: "2XU0oxnq2qxCpomAAuJY8K" },
    "The Rocks": { title: "Never Be the Same", artist: "Camila Cabello", spotifyId: "6n3fKnQyUU2wIzYcQEeu43" },
    "Manly Beach": { title: "The Middle", artist: "Zedd, Maren Morris, Grey", spotifyId: "2ARqIya5NAuvFVHSN3bL0m" },
    "Federation Square": { title: "Down Under", artist: "Men At Work", spotifyId: "1B8G0Pybu3V0b6xNQ2LLV0" },
    "Melbourne Cricket Ground": { title: "Somebody That I Used to Know", artist: "Gotye", spotifyId: "1qDrWA6lyx8cLECdZE7TV7" },
    "Royal Botanic Gardens": { title: "Torn", artist: "Natalie Imbruglia", spotifyId: "3LA4alRauE9xMGhkkwjqzL" },
    "Queen Victoria Market": { title: "Chandelier", artist: "Sia", spotifyId: "4VrWlk8IQxevMvERoX08iC" },
    "St Kilda Beach": { title: "Cheap Thrills", artist: "Sia", spotifyId: "27SdWb2rFzO6GWiYDBTD9j" },
    "Ovolo Laneways": { title: "Dance Monkey", artist: "Tones And I", spotifyId: "2XU0oxnq2qxCpomAAuJY8K" },
    "Great Northern Hotel": { title: "Never Be the Same", artist: "Camila Cabello", spotifyId: "6n3fKnQyUU2wIzYcQEeu43" },
    "Burj Khalifa": { title: "Lean On", artist: "Major Lazer & DJ Snake", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "Dubai Mall": { title: "One Dance", artist: "Drake", spotifyId: "1zi7xx7UVEFkmKfv06H8x0" },
    "Palm Jumeirah": { title: "Faded", artist: "Alan Walker", spotifyId: "7gHs73wELdeycvS48JfIos" },
    "Burj Al Arab": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "dubai marina": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Gold Souk": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Dubai Frame": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Jumeirah Beach": { title: "This Is What You Came For", artist: "Calvin Harris ft. Rihanna", spotifyId: "0azC730Exh71aQlOt9Zj3y" },
    "Museum of the Future": { title: "Titanium", artist: "David Guetta ft. Sia", spotifyId: "0lHAMNU8RGiIObScrsRgmP" },
    "Dubai Creek": { title: "Don't You Worry Child", artist: "Swedish House Mafia", spotifyId: "3bH4HzoZZFq8UpZmI2AMgV" },
    "Old City Hagia Sophia Hotel": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "Blue Mosque": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Topkapı Palace": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Grand Bazaar": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "Galata Tower": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
    "Bosphorus": { title: "Counting Stars", artist: "OneRepublic", spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
    "Basilica Cistern": { title: "Closer", artist: "The Chainsmokers", spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
    "Dolmabahçe Palace": { title: "Faded", artist: "Alan Walker", spotifyId: "7gHs73wELdeycvS48JfIos" },
    "Spice Bazaar": { title: "Something Just Like This", artist: "Coldplay & The Chainsmokers", spotifyId: "6RUKPb4LETWmmr3iAEQktW" },
    "İstiklal Avenue": { title: "Let Me Love You", artist: "DJ Snake", spotifyId: "0lYBSQXN6rCTvUZvg9S0lU" },
    "Great Pyramids of Giza": { title: "Walk Like an Egyptian", artist: "The Bangles", spotifyId: "0XPJbfBMOAyYjYmgYCbFr5" },
    "The Egyptian Museum": { title: "Desert Rose", artist: "Sting", spotifyId: "0J2TKGfnLfHMnjT9i6wCvU" },
    "Great Sphinx of Giza": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "Khan El Khalili Cafe": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "The Saladin Citadel of Cairo": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "Al Azhar Mosque": { title: "Uptown Funk", artist: "Bruno Mars", spotifyId: "32OlwWuMpZ6b0aN2RZOeMS" },
    "The Nile River": { title: "Happy", artist: "Pharrell Williams", spotifyId: "60nZcImufyMA1MKQY3dcCH" },
};

const defaultAirportMusic = {
    "ICN": { title: "Dynamite", artist: "BTS", spotifyId: "0t1kP63rueHleOhQkYSXFY" },
    "GMP": { title: "Dynamite", artist: "BTS", spotifyId: "0t1kP63rueHleOhQkYSXFY" },
    "PUS": { title: "Dynamite", artist: "BTS", spotifyId: "0t1kP63rueHleOhQkYSXFY" },
    "CJU": { title: "Dynamite", artist: "BTS", spotifyId: "0t1kP63rueHleOhQkYSXFY" },
    "NRT": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "HND": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "KIX": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "FUK": { title: "Gurenge", artist: "LiSA", spotifyId: "0hEXyhCgqiuDvh7yIuEcif" },
    "PEK": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "PVG": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "CAN": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "HKG": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "TPE": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "BKK": { title: "LALISA", artist: "LISA", spotifyId: "1DP7PGSwI13pvHAIKvluhd" },
    "HKT": { title: "LALISA", artist: "LISA", spotifyId: "1DP7PGSwI13pvHAIKvluhd" },
    "CNX": { title: "LALISA", artist: "LISA", spotifyId: "1DP7PGSwI13pvHAIKvluhd" },
    "SIN": { title: "Blinding Lights", artist: "The Weeknd", spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
    "SGN": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "HAN": { title: "Shape of You", artist: "Ed Sheeran", spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
    "LHR": { title: "London Calling", artist: "The Clash", spotifyId: "6vk0xhXh8cKMLjQfnMD0uH" },
    "EDI": { title: "London Calling", artist: "The Clash", spotifyId: "6vk0xhXh8cKMLjQfnMD0uH" },
    "CDG": { title: "La Vie en Rose", artist: "Edith Piaf", spotifyId: "6KBYk8OFtod7brGuZ3Y67c" },
    "NCE": { title: "La Vie en Rose", artist: "Edith Piaf", spotifyId: "6KBYk8OFtod7brGuZ3Y67c" },
    "FCO": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "MXP": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "VCE": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "FLR": { title: "Volare", artist: "Dean Martin", spotifyId: "0dB2dPrjeLPQGaRPG7SkBR" },
    "MAD": { title: "Waka Waka", artist: "Shakira", spotifyId: "2Cd9iWfcOpGDHLz6tVA3G4" },
    "BCN": { title: "Waka Waka", artist: "Shakira", spotifyId: "2Cd9iWfcOpGDHLz6tVA3G4" },
    "FRA": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "MUC": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "BER": { title: "99 Luftballons", artist: "Nena", spotifyId: "2uxN5XLEwqnpnaJ6vwqZj4" },
    "AMS": { title: "Levels", artist: "Avicii", spotifyId: "0xSAI2SQ9vTSLPCCPhTvHV" },
    "VIE": { title: "Rock Me Amadeus", artist: "Falco", spotifyId: "5Z01UMMf7V1o0MzF86s6WJ" },
    "PRG": { title: "The Moldau", artist: "Bedrich Smetana", spotifyId: "6k6EPsXkrrZSHAu14UEY1D" },
    "JFK": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "LAX": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "SFO": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "LAS": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "MIA": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "MCO": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "IAD": { title: "Empire State of Mind", artist: "JAY-Z, Alicia Keys", spotifyId: "2iUXsYOEPhVqEBwsqP70rE" },
    "SYD": { title: "Down Under", artist: "Men At Work", spotifyId: "1B8G0Pybu3V0b6xNQ2LLV0" },
    "MEL": { title: "Down Under", artist: "Men At Work", spotifyId: "1B8G0Pybu3V0b6xNQ2LLV0" },
    "DXB": { title: "Lean On", artist: "Major Lazer & DJ Snake", spotifyId: "1deiaRghBseqRfT03gHIPE" },
    "IST": { title: "Despacito", artist: "Luis Fonsi", spotifyId: "6habFhsOp2NvshLv26DqMb" },
    "CAI": { title: "Walk Like an Egyptian", artist: "The Bangles", spotifyId: "0XPJbfBMOAyYjYmgYCbFr5" },
};
