# UART0 (HW) for LoRa RX — interrupt driven
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# SPI0 for SW-UART TX4 (USB-VCOM display)
CONFIG_SPI=y
CONFIG_SOC_NRF52832_ALLOW_SPIM_DESPITE_PAN_58=y

# GPIO
CONFIG_GPIO=y

# RTT console for build-time debug
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Ring buffer for RX byte queuing
CONFIG_RING_BUFFER=y

# Reduce code size
CONFIG_BOOT_BANNER=n
