// catalog_data.dart — 100개 예시 카탈로그 데이터
// A~G: 텍스트 예시 (70개), H~J: 인터랙티브 예시 (30개)

class ExItem {
  final String no, title, category, categoryName, difficulty, hardware, type, description, pythonCode;
  final String? expectedOutput, flutterWidget;
  final List<String> steps;
  final List<Map<String, String>> concepts;
  final String quizQ, quizExplain;
  final List<String> quizOpts;
  final int quizAns;

  const ExItem({
    required this.no, required this.title, required this.category, required this.categoryName,
    required this.difficulty, required this.hardware, required this.type, required this.description,
    required this.pythonCode, this.expectedOutput, this.flutterWidget,
    required this.steps, required this.concepts,
    required this.quizQ, required this.quizOpts, required this.quizAns, required this.quizExplain,
  });
}

class CatInfo {
  final String code, name;
  final int iconCode;
  const CatInfo(this.code, this.name, this.iconCode);
}

const categories = [
  CatInfo('A', '첫걸음', 0xe8b5),      // Icons.terminal
  CatInfo('B', '숫자/계산', 0xe24a),    // Icons.calculate
  CatInfo('C', '조건문', 0xe0a1),       // Icons.alt_route
  CatInfo('D', '반복문', 0xe863),       // Icons.loop
  CatInfo('E', '함수', 0xea5b),         // Icons.functions
  CatInfo('F', '문자열', 0xe262),       // Icons.text_fields
  CatInfo('G', '리스트', 0xf107),       // Icons.list_alt
  CatInfo('H', '센서', 0xe51e),         // Icons.sensors
  CatInfo('I', '카메라/소리', 0xe3af),  // Icons.camera_alt
  CatInfo('J', '게임', 0xea28),         // Icons.sports_esports
];

final catalog = <ExItem>[
  // ═══════════════════════════════════════════
  //  A. 첫걸음 (기초, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(
    no: 'A01', title: 'Hello Python!', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'Python에서 가장 먼저 배우는 print() 명령으로 화면에 글자를 표시해봅시다.',
    pythonCode: "# 화면에 인사말 표시하기\nprint('Hello Python!')\nprint('안녕하세요!')\n\nname = '학생'\nprint(f'{name}님, 환영합니다!')\nprint(f'1 + 2 = {1 + 2}')",
    expectedOutput: "Hello Python!\n안녕하세요!\n\n학생님, 환영합니다!\n1 + 2 = 3",
    steps: ['print()로 텍스트를 출력합니다', 'name 변수에 이름을 저장합니다', 'f-string으로 변수를 문장에 넣습니다'],
    concepts: [{'term': 'print()', 'desc': '괄호 안의 내용을 화면에 보여주는 명령이에요.'}, {'term': '변수', 'desc': '데이터를 담는 상자예요. name = "학생"처럼 사용해요.'}, {'term': 'f-string', 'desc': "f'...'로 쓰면 {변수}를 문자열 안에 넣을 수 있어요."}],
    quizQ: "print('Hello')를 실행하면?", quizOpts: ['Hello', 'print', "print('Hello')", '에러'], quizAns: 0, quizExplain: "print()는 괄호 안의 내용을 화면에 보여줍니다!",
  ),
  const ExItem(
    no: 'A02', title: '현재 시간 표시하기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'datetime 모듈로 현재 날짜와 시간을 가져와 화면에 표시합니다.',
    pythonCode: "from datetime import datetime\n\nnow = datetime.now()\nprint(f'날짜: {now.year}년 {now.month}월 {now.day}일')\nprint(f'시간: {now.hour}시 {now.minute}분')\nprint(f'요일: {now.strftime(\"%A\")}')",
    expectedOutput: "날짜: 2026년 4월 19일\n시간: 14시 30분\n요일: Sunday",
    steps: ['datetime 모듈을 가져옵니다', 'now()로 현재 시각을 얻습니다', 'year, month, day로 분리 출력합니다'],
    concepts: [{'term': 'import', 'desc': '다른 사람이 만든 도구(모듈)를 가져오는 명령이에요.'}, {'term': 'datetime.now()', 'desc': '현재 날짜와 시간을 알려주는 함수예요.'}, {'term': '.year, .month', 'desc': '점(.)으로 객체의 세부 정보에 접근할 수 있어요.'}],
    quizQ: 'datetime.now()는 무엇을 반환하나요?', quizOpts: ['현재 날짜만', '현재 시간만', '현재 날짜와 시간', '어제 날짜'], quizAns: 2, quizExplain: 'now()는 날짜와 시간을 모두 포함한 객체를 반환해요!',
  ),
  const ExItem(
    no: 'A03', title: '구구단 출력하기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'for 반복문으로 구구단을 출력합니다. 원하는 단을 바꿔보세요!',
    pythonCode: "dan = 3\nprint(f'=== {dan}단 ===')\nfor i in range(1, 10):\n    print(f'{dan} x {i} = {dan * i}')",
    expectedOutput: "=== 3단 ===\n3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27",
    steps: ['dan 변수에 원하는 단을 넣습니다', 'for문으로 1~9까지 반복합니다', '각 줄에 곱셈 결과를 출력합니다'],
    concepts: [{'term': 'for문', 'desc': '같은 동작을 여러 번 반복하는 명령이에요.'}, {'term': 'range(1, 10)', 'desc': '1부터 9까지 숫자를 만들어줘요. 끝 숫자(10)는 포함 안 돼요.'}, {'term': '변수 활용', 'desc': 'dan = 3을 바꾸면 다른 단이 나와요.'}],
    quizQ: 'range(1, 10)은 몇 개의 숫자?', quizOpts: ['10개', '9개', '8개', '11개'], quizAns: 1, quizExplain: '1~9까지 총 9개! 끝 숫자 10은 포함 안 돼요.',
  ),
  const ExItem(
    no: 'A04', title: '이름 입력받아 인사하기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'input()으로 사용자에게 이름을 입력받고 맞춤 인사를 합니다.',
    pythonCode: "name = input('이름을 입력하세요: ')\nage = int(input('나이를 입력하세요: '))\n\nprint(f'안녕하세요, {name}님!')\nprint(f'{name}님은 {age}살이시군요!')\nprint(f'{100 - age}년 후면 100살이에요!')",
    expectedOutput: "이름을 입력하세요: 민수\n나이를 입력하세요: 13\n안녕하세요, 민수님!\n민수님은 13살이시군요!\n87년 후면 100살이에요!",
    steps: ['input()으로 이름을 입력받습니다', 'int()로 나이를 숫자로 변환합니다', 'f-string으로 맞춤 메시지를 출력합니다'],
    concepts: [{'term': 'input()', 'desc': '사용자에게 키보드 입력을 받는 함수예요.'}, {'term': 'int()', 'desc': '문자열을 정수(숫자)로 바꿔주는 함수예요.'}, {'term': '문자열 연결', 'desc': 'f-string으로 변수와 텍스트를 섞을 수 있어요.'}],
    quizQ: 'input()은 항상 어떤 타입을 반환하나요?', quizOpts: ['정수', '실수', '문자열', '리스트'], quizAns: 2, quizExplain: 'input()은 항상 문자열(str)을 반환해요. 숫자로 쓰려면 int()로 변환!',
  ),
  const ExItem(
    no: 'A05', title: '숫자 맞추기 게임', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'random으로 비밀 숫자를 만들고 맞춰보는 게임입니다.',
    pythonCode: "import random\n\nsecret = random.randint(1, 10)\nguess = 7\n\nprint(f'비밀 숫자: {secret}')\nprint(f'나의 추측: {guess}')\n\nif guess == secret:\n    print('정답!')\nelif guess > secret:\n    print('너무 커요!')\nelse:\n    print('너무 작아요!')",
    expectedOutput: "비밀 숫자: 5\n나의 추측: 7\n너무 커요!",
    steps: ['1~10 비밀 숫자가 생성됩니다', 'guess에 추측 숫자를 넣습니다', 'if/elif/else로 결과를 판별합니다'],
    concepts: [{'term': 'random.randint()', 'desc': '범위 내 랜덤 정수를 만들어요.'}, {'term': 'if/elif/else', 'desc': '조건에 따라 다른 코드를 실행해요.'}, {'term': '== (비교)', 'desc': '두 값이 같은지 비교하는 연산자예요.'}],
    quizQ: 'if/elif/else 중 먼저 검사되는 것은?', quizOpts: ['else', 'elif', 'if', '순서 없음'], quizAns: 2, quizExplain: 'if가 먼저! 거짓이면 elif, 모두 거짓이면 else!',
  ),
  const ExItem(
    no: 'A06', title: '별 피라미드 그리기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: '반복문과 문자열 곱셈(*)으로 별 피라미드를 그립니다.',
    pythonCode: "n = 5\nfor i in range(1, n + 1):\n    spaces = ' ' * (n - i)\n    stars = '*' * (2 * i - 1)\n    print(spaces + stars)",
    expectedOutput: "    *\n   ***\n  *****\n *******\n*********",
    steps: ['n에 피라미드 높이를 지정합니다', '각 줄마다 공백과 별 개수를 계산합니다', '문자열 곱셈(*)으로 반복 출력합니다'],
    concepts: [{'term': "'*' * 3", 'desc': "문자열에 *를 하면 반복돼요. '*' * 3 = '***'"}, {'term': '공백 정렬', 'desc': '앞에 공백을 넣어서 가운데 정렬 효과를 만들어요.'}, {'term': '패턴 관찰', 'desc': '1줄: 별1개, 2줄: 별3개, 3줄: 별5개... 규칙을 찾아요.'}],
    quizQ: "'*' * 4의 결과는?", quizOpts: ['*4', '****', '* * * *', '에러'], quizAns: 1, quizExplain: "문자열 * 숫자는 반복! '*' * 4 = '****'",
  ),
  const ExItem(
    no: 'A07', title: '나의 프로필 카드', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: '여러 변수에 정보를 저장하고 깔끔한 프로필 카드를 출력합니다.',
    pythonCode: "name = '김민수'\nage = 13\nschool = '서울중학교'\nhobby = '코딩'\n\nprint('=' * 20)\nprint(f'  이름: {name}')\nprint(f'  나이: {age}살')\nprint(f'  학교: {school}')\nprint(f'  취미: {hobby}')\nprint('=' * 20)",
    expectedOutput: "====================\n  이름: 김민수\n  나이: 13살\n  학교: 서울중학교\n  취미: 코딩\n====================",
    steps: ['변수에 개인 정보를 저장합니다', '구분선(=)으로 카드 테두리를 만듭니다', 'f-string으로 정보를 출력합니다'],
    concepts: [{'term': '여러 변수', 'desc': '각각의 정보를 별도 변수에 저장하면 관리가 쉬워요.'}, {'term': "문자열 * 숫자", 'desc': "'=' * 20은 =를 20번 반복해요."}, {'term': '포맷팅', 'desc': 'f-string으로 변수를 문장에 자연스럽게 넣을 수 있어요.'}],
    quizQ: "변수 age = 13일 때 type(age)는?", quizOpts: ['str', 'int', 'float', 'bool'], quizAns: 1, quizExplain: '13은 정수이므로 int(정수) 타입이에요!',
  ),
  const ExItem(
    no: 'A08', title: '온도 변환기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: '섭씨를 화씨로, 화씨를 섭씨로 변환하는 프로그램입니다.',
    pythonCode: "celsius = 36.5\nfahrenheit = celsius * 9/5 + 32\nprint(f'섭씨 {celsius}도 = 화씨 {fahrenheit:.1f}도')\n\nf = 100\nc = (f - 32) * 5/9\nprint(f'화씨 {f}도 = 섭씨 {c:.1f}도')",
    expectedOutput: "섭씨 36.5도 = 화씨 97.7도\n화씨 100도 = 섭씨 37.8도",
    steps: ['섭씨 온도를 변수에 저장합니다', '공식으로 화씨를 계산합니다', ':.1f로 소수점 1자리로 표시합니다'],
    concepts: [{'term': '수식', 'desc': 'Python에서 수학 공식을 그대로 쓸 수 있어요.'}, {'term': ':.1f', 'desc': '소수점 아래 1자리까지만 표시하는 포맷이에요.'}, {'term': '변환 공식', 'desc': 'F = C × 9/5 + 32, C = (F - 32) × 5/9'}],
    quizQ: '물이 끓는 온도는 섭씨 몇 도?', quizOpts: ['0도', '36.5도', '100도', '212도'], quizAns: 2, quizExplain: '물은 섭씨 100도(화씨 212도)에서 끓어요!',
  ),
  const ExItem(
    no: 'A09', title: 'BMI 계산기', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: '키와 몸무게로 BMI를 계산하고 판정 결과를 알려줍니다.',
    pythonCode: "height = 165  # cm\nweight = 55   # kg\n\nbmi = weight / (height / 100) ** 2\nprint(f'키: {height}cm, 몸무게: {weight}kg')\nprint(f'BMI: {bmi:.1f}')\n\nif bmi < 18.5:\n    print('저체중')\nelif bmi < 25:\n    print('정상')\nelif bmi < 30:\n    print('과체중')\nelse:\n    print('비만')",
    expectedOutput: "키: 165cm, 몸무게: 55kg\nBMI: 20.2\n정상",
    steps: ['키와 몸무게를 입력합니다', 'BMI 공식으로 계산합니다', '범위에 따라 판정합니다'],
    concepts: [{'term': '** (거듭제곱)', 'desc': '2 ** 3 = 8처럼 거듭제곱을 계산해요.'}, {'term': 'BMI 공식', 'desc': 'BMI = 체중(kg) / 키(m)²'}, {'term': '범위 조건', 'desc': 'elif로 여러 범위를 순서대로 검사할 수 있어요.'}],
    quizQ: '** 연산자는 무슨 뜻?', quizOpts: ['곱셈', '나눗셈', '거듭제곱', '나머지'], quizAns: 2, quizExplain: '** 는 거듭제곱이에요. 2**3 = 2×2×2 = 8!',
  ),
  const ExItem(
    no: 'A10', title: '가위바위보 게임', category: 'A', categoryName: '첫걸음',
    difficulty: '기초', hardware: '화면', type: 'text',
    description: 'random.choice로 컴퓨터의 선택을 만들고 승패를 판정합니다.',
    pythonCode: "import random\n\nchoices = ['가위', '바위', '보']\nuser = '가위'\ncom = random.choice(choices)\n\nprint(f'나: {user}')\nprint(f'컴퓨터: {com}')\n\nif user == com:\n    print('비겼습니다!')\nelif (user=='가위' and com=='보') or \\\n     (user=='바위' and com=='가위') or \\\n     (user=='보' and com=='바위'):\n    print('이겼습니다!')\nelse:\n    print('졌습니다!')",
    expectedOutput: "나: 가위\n컴퓨터: 보\n이겼습니다!",
    steps: ['선택지 리스트를 만듭니다', 'random.choice()로 컴퓨터가 선택합니다', '승패 조건을 비교합니다'],
    concepts: [{'term': 'random.choice()', 'desc': '리스트에서 하나를 랜덤으로 골라요.'}, {'term': 'and / or', 'desc': '여러 조건을 결합하는 논리 연산자예요.'}, {'term': '리스트', 'desc': "['가위','바위','보']처럼 여러 값을 담는 자료구조예요."}],
    quizQ: "random.choice(['A','B','C'])는?", quizOpts: ['항상 A', 'A,B,C 중 하나', 'ABC', '에러'], quizAns: 1, quizExplain: 'choice()는 리스트에서 하나를 랜덤으로 골라요!',
  ),

  // ═══════════════════════════════════════════
  //  B. 숫자와 계산 (기초, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'B01', title: '사칙연산 계산기', category: 'B', categoryName: '숫자/계산', difficulty: '기초', hardware: '화면', type: 'text', description: 'Python으로 덧셈, 뺄셈, 곱셈, 나눗셈, 몫, 나머지를 계산합니다.', pythonCode: "a, b = 15, 4\nprint(f'{a} + {b} = {a+b}')\nprint(f'{a} - {b} = {a-b}')\nprint(f'{a} * {b} = {a*b}')\nprint(f'{a} / {b} = {a/b}')\nprint(f'{a} // {b} = {a//b}')\nprint(f'{a} % {b} = {a%b}')", expectedOutput: "15 + 4 = 19\n15 - 4 = 11\n15 * 4 = 60\n15 / 4 = 3.75\n15 // 4 = 3\n15 % 4 = 3", steps: ['두 숫자를 변수에 넣습니다', '사칙연산을 수행합니다', '몫(//)과 나머지(%)도 계산합니다'], concepts: [{'term': '사칙연산', 'desc': '+,-,*,/로 기본 계산을 해요.'}, {'term': '//', 'desc': '나눗셈의 몫(정수 부분)만 반환해요.'}, {'term': '%', 'desc': '나눈 뒤 남는 나머지를 반환해요.'}], quizQ: '15 // 4의 결과는?', quizOpts: ['3.75', '3', '4', '0'], quizAns: 1, quizExplain: '//는 몫만 반환! 15÷4=3...3이므로 몫은 3!'),
  const ExItem(no: 'B02', title: '짝수/홀수 판별기', category: 'B', categoryName: '숫자/계산', difficulty: '기초', hardware: '화면', type: 'text', description: '나머지 연산(%)으로 숫자가 짝수인지 홀수인지 판별합니다.', pythonCode: "for num in [1, 2, 7, 10, 15, 20]:\n    if num % 2 == 0:\n        print(f'{num}: 짝수')\n    else:\n        print(f'{num}: 홀수')", expectedOutput: "1: 홀수\n2: 짝수\n7: 홀수\n10: 짝수\n15: 홀수\n20: 짝수", steps: ['여러 숫자를 리스트로 준비합니다', '% 2로 나머지를 구합니다', '나머지가 0이면 짝수, 아니면 홀수'], concepts: [{'term': '% (나머지)', 'desc': '나눈 나머지를 구해요. 짝수는 2로 나누면 나머지 0!'}, {'term': 'for in 리스트', 'desc': '리스트의 각 요소를 하나씩 꺼내 반복해요.'}, {'term': '== 0', 'desc': '나머지가 0인지 비교하는 조건이에요.'}], quizQ: '7 % 2의 결과는?', quizOpts: ['0', '1', '3', '3.5'], quizAns: 1, quizExplain: '7÷2=3...1이므로 나머지는 1! 홀수예요.'),
  const ExItem(no: 'B03', title: '최대공약수 구하기', category: 'B', categoryName: '숫자/계산', difficulty: '중급', hardware: '화면', type: 'text', description: '유클리드 알고리즘으로 두 수의 최대공약수(GCD)를 구합니다.', pythonCode: "a, b = 48, 18\nprint(f'{a}와 {b}의 최대공약수 구하기')\n\nx, y = a, b\nwhile y != 0:\n    x, y = y, x % y\n    print(f'  → {x}, {y}')\n\nprint(f'최대공약수: {x}')", expectedOutput: "48와 18의 최대공약수 구하기\n  → 18, 12\n  → 12, 6\n  → 6, 0\n최대공약수: 6", steps: ['두 숫자를 준비합니다', '큰 수를 작은 수로 나눈 나머지를 반복 구합니다', '나머지가 0이 되면 그 수가 GCD입니다'], concepts: [{'term': '유클리드 알고리즘', 'desc': '나머지를 반복해서 구하면 최대공약수를 찾을 수 있어요.'}, {'term': 'while', 'desc': '조건이 참인 동안 계속 반복하는 명령이에요.'}, {'term': '다중 대입', 'desc': 'x, y = y, x%y로 두 변수를 동시에 바꿀 수 있어요.'}], quizQ: '12와 8의 최대공약수는?', quizOpts: ['2', '4', '6', '8'], quizAns: 1, quizExplain: '12=4×3, 8=4×2이므로 최대공약수는 4!'),
  const ExItem(no: 'B04', title: '소수 판별기', category: 'B', categoryName: '숫자/계산', difficulty: '중급', hardware: '화면', type: 'text', description: '어떤 숫자가 소수(1과 자신만으로 나누어지는 수)인지 판별합니다.', pythonCode: "num = 17\nprint(f'{num}은(는) 소수일까?')\n\nis_prime = True\nif num < 2:\n    is_prime = False\nfor i in range(2, int(num**0.5) + 1):\n    if num % i == 0:\n        is_prime = False\n        break\n\nprint(f'{num}은(는) {\"소수\" if is_prime else \"소수가 아님\"}')", expectedOutput: "17은(는) 소수일까?\n17은(는) 소수", steps: ['판별할 숫자를 정합니다', '2부터 √n까지 나누어보며 확인합니다', '나누어떨어지면 소수가 아닙니다'], concepts: [{'term': '소수', 'desc': '1과 자기 자신만으로 나누어지는 수예요. 2,3,5,7,11...'}, {'term': 'break', 'desc': '반복문을 즉시 빠져나오는 명령이에요.'}, {'term': 'num**0.5', 'desc': '제곱근을 구해요. √17 ≈ 4.1이므로 4까지만 검사하면 돼요.'}], quizQ: '다음 중 소수가 아닌 것은?', quizOpts: ['2', '7', '9', '11'], quizAns: 2, quizExplain: '9 = 3×3이므로 소수가 아니에요!'),
  const ExItem(no: 'B05', title: '팩토리얼 계산', category: 'B', categoryName: '숫자/계산', difficulty: '기초', hardware: '화면', type: 'text', description: '팩토리얼(n!)은 1부터 n까지 모두 곱한 값입니다.', pythonCode: "n = 5\nresult = 1\nprocess = ''\n\nfor i in range(1, n + 1):\n    result *= i\n    process += str(i)\n    if i < n:\n        process += ' × '\n\nprint(f'{n}! = {process} = {result}')", expectedOutput: "5! = 1 × 2 × 3 × 4 × 5 = 120", steps: ['n에 숫자를 정합니다', '1부터 n까지 차례로 곱합니다', '곱셈 과정과 결과를 출력합니다'], concepts: [{'term': '팩토리얼 (!)', 'desc': '5! = 1×2×3×4×5 = 120. 계단식으로 곱하는 거예요.'}, {'term': '*= (복합 대입)', 'desc': 'result *= i는 result = result * i와 같아요.'}, {'term': '누적 곱', 'desc': '반복하면서 값을 계속 곱해가는 패턴이에요.'}], quizQ: '4!의 값은?', quizOpts: ['4', '16', '24', '64'], quizAns: 2, quizExplain: '4! = 1×2×3×4 = 24!'),
  const ExItem(no: 'B06', title: '피보나치 수열', category: 'B', categoryName: '숫자/계산', difficulty: '중급', hardware: '화면', type: 'text', description: '피보나치 수열: 앞의 두 수를 더해서 다음 수를 만드는 수열입니다.', pythonCode: "n = 10\na, b = 0, 1\nfib = []\n\nfor _ in range(n):\n    fib.append(a)\n    a, b = b, a + b\n\nprint(f'피보나치 수열 (처음 {n}개):')\nprint(fib)", expectedOutput: "피보나치 수열 (처음 10개):\n[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]", steps: ['처음 두 수 0, 1로 시작합니다', '앞의 두 수를 더해 다음 수를 만듭니다', 'n개까지 반복합니다'], concepts: [{'term': '피보나치', 'desc': '0, 1, 1, 2, 3, 5, 8... 앞 두 수의 합이 다음 수예요.'}, {'term': 'a, b = b, a+b', 'desc': '동시에 두 변수를 업데이트하는 기법이에요.'}, {'term': 'append()', 'desc': '리스트 끝에 새 요소를 추가하는 메서드예요.'}], quizQ: '피보나치에서 5 다음 수는?', quizOpts: ['6', '7', '8', '10'], quizAns: 2, quizExplain: '3+5=8! 피보나치는 앞 두 수의 합이에요.'),
  const ExItem(no: 'B07', title: '진법 변환기', category: 'B', categoryName: '숫자/계산', difficulty: '중급', hardware: '화면', type: 'text', description: '10진수를 2진수, 8진수, 16진수로 변환합니다.', pythonCode: "num = 42\nprint(f'10진수: {num}')\nprint(f' 2진수: {bin(num)}')\nprint(f' 8진수: {oct(num)}')\nprint(f'16진수: {hex(num)}')\nprint(f'\\n숫자로만:')\nprint(f' 2진수: {num:b}')\nprint(f' 8진수: {num:o}')\nprint(f'16진수: {num:x}')", expectedOutput: "10진수: 42\n 2진수: 0b101010\n 8진수: 0o52\n16진수: 0x2a\n\n숫자로만:\n 2진수: 101010\n 8진수: 52\n16진수: 2a", steps: ['10진수 숫자를 정합니다', 'bin/oct/hex 함수로 변환합니다', '포맷 문자(:b, :o, :x)로도 표시합니다'], concepts: [{'term': 'bin()', 'desc': '10진수를 2진수 문자열로 바꿔요. 0b 접두어 포함.'}, {'term': 'hex()', 'desc': '10진수를 16진수로 바꿔요. 0~9, a~f 사용.'}, {'term': '진법', 'desc': '2진법: 0과1만, 8진법: 0~7, 16진법: 0~f 사용.'}], quizQ: '10진수 10은 2진수로?', quizOpts: ['10', '1010', '1100', '1001'], quizAns: 1, quizExplain: '10 = 8+2 = 1×2³ + 0×2² + 1×2¹ + 0×2⁰ = 1010!'),
  const ExItem(no: 'B08', title: '평균/최대/최소 구하기', category: 'B', categoryName: '숫자/계산', difficulty: '기초', hardware: '화면', type: 'text', description: '리스트의 합계, 평균, 최대, 최소를 내장 함수로 구합니다.', pythonCode: "scores = [85, 92, 78, 96, 88]\n\nprint(f'점수: {scores}')\nprint(f'합계: {sum(scores)}')\nprint(f'평균: {sum(scores)/len(scores):.1f}')\nprint(f'최고: {max(scores)}')\nprint(f'최저: {min(scores)}')\nprint(f'개수: {len(scores)}')", expectedOutput: "점수: [85, 92, 78, 96, 88]\n합계: 439\n평균: 87.8\n최고: 96\n최저: 78\n개수: 5", steps: ['점수 리스트를 만듭니다', 'sum, max, min 함수를 사용합니다', 'len으로 개수를 세어 평균을 구합니다'], concepts: [{'term': 'sum()', 'desc': '리스트의 모든 값을 더해줘요.'}, {'term': 'max() / min()', 'desc': '가장 큰 값 / 가장 작은 값을 찾아요.'}, {'term': 'len()', 'desc': '리스트에 몇 개의 요소가 있는지 세어요.'}], quizQ: 'sum([1,2,3])의 결과는?', quizOpts: ['123', '3', '6', '[1,2,3]'], quizAns: 2, quizExplain: 'sum()은 모든 요소를 더해요! 1+2+3=6'),
  const ExItem(no: 'B09', title: '원의 넓이와 둘레', category: 'B', categoryName: '숫자/계산', difficulty: '기초', hardware: '화면', type: 'text', description: 'math.pi로 원의 넓이와 둘레를 계산합니다.', pythonCode: "import math\n\nr = 5\narea = math.pi * r ** 2\ncircum = 2 * math.pi * r\n\nprint(f'반지름: {r}')\nprint(f'원의 넓이: {area:.2f}')\nprint(f'원의 둘레: {circum:.2f}')\nprint(f'파이(π): {math.pi:.4f}')", expectedOutput: "반지름: 5\n원의 넓이: 78.54\n원의 둘레: 31.42\n파이(π): 3.1416", steps: ['반지름을 정합니다', 'math.pi로 파이 값을 사용합니다', '넓이=πr², 둘레=2πr 공식을 적용합니다'], concepts: [{'term': 'math.pi', 'desc': '원주율 π ≈ 3.14159... 을 정확하게 가져와요.'}, {'term': '넓이 공식', 'desc': '원의 넓이 = π × 반지름²'}, {'term': ':.2f', 'desc': '소수점 아래 2자리까지만 표시해요.'}], quizQ: '반지름 3인 원의 둘레 공식은?', quizOpts: ['π × 3', '2π × 3', 'π × 9', '6'], quizAns: 1, quizExplain: '원의 둘레 = 2πr = 2 × π × 3 ≈ 18.85'),
  const ExItem(no: 'B10', title: '복리 이자 계산기', category: 'B', categoryName: '숫자/계산', difficulty: '중급', hardware: '화면', type: 'text', description: '복리로 돈이 얼마나 불어나는지 계산합니다.', pythonCode: "principal = 1000000  # 원금 100만원\nrate = 0.05  # 연 5%\nyears = 5\n\namount = principal\nfor y in range(1, years + 1):\n    amount *= (1 + rate)\n    print(f'{y}년 후: {amount:,.0f}원')\n\nprint(f'\\n원금: {principal:,}원')\nprint(f'이자: {amount - principal:,.0f}원')", expectedOutput: "1년 후: 1,050,000원\n2년 후: 1,102,500원\n3년 후: 1,157,625원\n4년 후: 1,215,506원\n5년 후: 1,276,282원\n\n원금: 1,000,000원\n이자: 276,282원", steps: ['원금, 이율, 기간을 설정합니다', '매년 이자를 곱해 나갑니다', '최종 금액과 이자 합계를 출력합니다'], concepts: [{'term': '복리', 'desc': '이자에 이자가 붙는 방식이에요. 시간이 갈수록 빠르게 늘어나요.'}, {'term': ':, (천 단위)', 'desc': '{amount:,}로 1,000,000처럼 쉼표를 넣어요.'}, {'term': '누적 곱', 'desc': '매년 (1+이율)을 곱해가면 복리가 계산돼요.'}], quizQ: '100만원 연 5% 1년 복리 이자는?', quizOpts: ['5,000원', '50,000원', '500,000원', '100,000원'], quizAns: 1, quizExplain: '100만 × 0.05 = 5만원!'),

  // ═══════════════════════════════════════════
  //  C. 조건문 (기초, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'C01', title: '성적 등급 매기기', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '점수에 따라 A~F 등급을 매기는 프로그램입니다.', pythonCode: "score = 85\n\nif score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelif score >= 70:\n    grade = 'C'\nelif score >= 60:\n    grade = 'D'\nelse:\n    grade = 'F'\n\nprint(f'점수: {score}점 → 등급: {grade}')", expectedOutput: "점수: 85점 → 등급: B", steps: ['점수를 입력합니다', 'if/elif/else로 범위를 체크합니다', '해당하는 등급을 출력합니다'], concepts: [{'term': 'if/elif/else', 'desc': '위에서부터 조건을 검사하며, 처음 참인 곳이 실행돼요.'}, {'term': '>= (이상)', 'desc': '크거나 같음을 비교하는 연산자예요.'}, {'term': '범위 검사', 'desc': '높은 점수부터 검사하면 elif로 범위를 구분할 수 있어요.'}], quizQ: '75점은 어떤 등급?', quizOpts: ['A', 'B', 'C', 'D'], quizAns: 2, quizExplain: '70이상 80미만이므로 C등급!'),
  const ExItem(no: 'C02', title: '윤년 판별기', category: 'C', categoryName: '조건문', difficulty: '중급', hardware: '화면', type: 'text', description: '복합 조건문으로 윤년인지 판별합니다.', pythonCode: "year = 2024\n\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print(f'{year}년은 윤년입니다!')\n    print('2월이 29일까지 있어요.')\nelse:\n    print(f'{year}년은 평년입니다.')\n    print('2월이 28일까지예요.')", expectedOutput: "2024년은 윤년입니다!\n2월이 29일까지 있어요.", steps: ['연도를 입력합니다', '윤년 조건(4배수 && !100배수 || 400배수)을 검사합니다', '결과를 출력합니다'], concepts: [{'term': 'and', 'desc': '두 조건이 모두 참일 때만 참이에요.'}, {'term': 'or', 'desc': '두 조건 중 하나만 참이면 참이에요.'}, {'term': '윤년 규칙', 'desc': '4로 나누어지면 윤년, 100으로도 나누어지면 평년, 400으로 나누어지면 윤년!'}], quizQ: '1900년은 윤년인가요?', quizOpts: ['윤년', '평년', '알 수 없음', '오류'], quizAns: 1, quizExplain: '100으로 나누어지지만 400으로는 안 나누어지므로 평년!'),
  const ExItem(no: 'C03', title: '계절 판별기', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '월(1~12)을 입력하면 어떤 계절인지 알려줍니다.', pythonCode: "month = 4\n\nif month in [3, 4, 5]:\n    season = '봄 🌸'\nelif month in [6, 7, 8]:\n    season = '여름 ☀️'\nelif month in [9, 10, 11]:\n    season = '가을 🍂'\nelse:\n    season = '겨울 ❄️'\n\nprint(f'{month}월은 {season}입니다.')", expectedOutput: "4월은 봄 🌸입니다.", steps: ['월을 입력합니다', 'in 연산자로 해당 월이 어떤 리스트에 있는지 검사합니다', '계절 이름을 출력합니다'], concepts: [{'term': 'in 연산자', 'desc': '값이 리스트 안에 있는지 확인해요. 3 in [3,4,5]는 True!'}, {'term': 'elif 체이닝', 'desc': '여러 조건을 순서대로 검사하는 패턴이에요.'}, {'term': '리스트 멤버십', 'desc': '[3,4,5]처럼 묶어서 한번에 검사할 수 있어요.'}], quizQ: '7 in [6,7,8]의 결과는?', quizOpts: ['True', 'False', '7', '에러'], quizAns: 0, quizExplain: '7은 [6,7,8] 리스트 안에 있으므로 True!'),
  const ExItem(no: 'C04', title: '삼각형 종류 판별', category: 'C', categoryName: '조건문', difficulty: '중급', hardware: '화면', type: 'text', description: '세 변의 길이로 삼각형의 종류를 판별합니다.', pythonCode: "a, b, c = 3, 4, 5\n\nprint(f'세 변: {a}, {b}, {c}')\n\nif a + b <= c or a + c <= b or b + c <= a:\n    print('삼각형이 아닙니다!')\nelif a == b == c:\n    print('정삼각형')\nelif a == b or b == c or a == c:\n    print('이등변삼각형')\nelse:\n    print('일반 삼각형')\n\nif a**2 + b**2 == c**2:\n    print('(직각삼각형!)')", expectedOutput: "세 변: 3, 4, 5\n일반 삼각형\n(직각삼각형!)", steps: ['세 변의 길이를 입력합니다', '삼각형 성립 조건을 먼저 확인합니다', '변의 관계로 종류를 판별합니다'], concepts: [{'term': '삼각형 조건', 'desc': '두 변의 합이 나머지 한 변보다 커야 삼각형이 돼요.'}, {'term': 'a == b == c', 'desc': '세 값이 모두 같은지 비교하는 표현이에요.'}, {'term': '피타고라스', 'desc': 'a²+b²=c²이면 직각삼각형! 3²+4²=5²'}], quizQ: '세 변이 5,5,5인 삼각형은?', quizOpts: ['일반', '이등변', '정삼각형', '직각'], quizAns: 2, quizExplain: '세 변이 모두 같으면 정삼각형!'),
  const ExItem(no: 'C05', title: '택시 요금 계산기', category: 'C', categoryName: '조건문', difficulty: '중급', hardware: '화면', type: 'text', description: '거리에 따라 구간별 택시 요금을 계산합니다.', pythonCode: "distance = 7.5  # km\nbase_fare = 4800  # 기본요금\nbase_dist = 2.0   # 기본거리\n\nif distance <= base_dist:\n    fare = base_fare\nelse:\n    extra = distance - base_dist\n    fare = base_fare + int(extra / 0.131) * 100\n\nprint(f'거리: {distance}km')\nprint(f'요금: {fare:,}원')", expectedOutput: "거리: 7.5km\n요금: 8,900원", steps: ['이동 거리를 입력합니다', '기본거리 이내면 기본요금입니다', '초과분에 대해 거리당 추가요금을 계산합니다'], concepts: [{'term': '구간별 요금', 'desc': '기본거리까지는 고정요금, 이후 거리별 추가요금이 붙어요.'}, {'term': 'int()', 'desc': '소수점을 버리고 정수로 바꿔요. int(4.7) = 4'}, {'term': ':, (천단위)', 'desc': '{8900:,}이면 8,900처럼 쉼표가 들어가요.'}], quizQ: '기본거리 이하로 타면 요금은?', quizOpts: ['무료', '기본요금', '거리×단가', '에러'], quizAns: 1, quizExplain: '기본거리(2km) 이내면 기본요금만 나와요!'),
  const ExItem(no: 'C06', title: '로그인 시뮬레이션', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '아이디와 비밀번호를 확인하는 간단한 로그인 시스템입니다.', pythonCode: "correct_id = 'admin'\ncorrect_pw = '1234'\n\nuser_id = 'admin'\nuser_pw = '1234'\n\nprint(f'입력 ID: {user_id}')\nprint(f'입력 PW: {\"*\" * len(user_pw)}')\n\nif user_id == correct_id and user_pw == correct_pw:\n    print('로그인 성공!')\nelif user_id != correct_id:\n    print('아이디가 틀렸습니다.')\nelse:\n    print('비밀번호가 틀렸습니다.')", expectedOutput: "입력 ID: admin\n입력 PW: ****\n로그인 성공!", steps: ['정답 아이디/비밀번호를 설정합니다', '사용자 입력과 비교합니다', '결과에 따라 메시지를 출력합니다'], concepts: [{'term': '== (문자열 비교)', 'desc': '두 문자열이 정확히 같은지 비교해요.'}, {'term': 'and (그리고)', 'desc': 'ID도 맞고 PW도 맞아야 로그인 성공!'}, {'term': '비밀번호 마스킹', 'desc': '"*" * 4로 비밀번호를 ****로 숨겨요.'}], quizQ: "'abc' == 'ABC'의 결과는?", quizOpts: ['True', 'False', '에러', '0'], quizAns: 1, quizExplain: "Python에서 문자열 비교는 대소문자를 구분해요!"),
  const ExItem(no: 'C07', title: '놀이공원 입장료', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '나이와 인원수에 따라 놀이공원 입장료를 계산합니다.', pythonCode: "age = 10\ncount = 3\n\nif age < 4:\n    price = 0\n    category = '무료(영유아)'\nelif age < 13:\n    price = 15000\n    category = '어린이'\nelif age < 19:\n    price = 20000\n    category = '청소년'\nelse:\n    price = 30000\n    category = '성인'\n\ntotal = price * count\nif count >= 3:\n    total = int(total * 0.9)\n    print('3인 이상 10% 할인!')\n\nprint(f'{category} {count}명: {total:,}원')", expectedOutput: "3인 이상 10% 할인!\n어린이 3명: 40,500원", steps: ['나이로 가격 구간을 정합니다', '인원수를 곱해 총 금액을 구합니다', '3명 이상이면 10% 할인합니다'], concepts: [{'term': '다중 elif', 'desc': '나이 범위를 여러 구간으로 나눠 검사해요.'}, {'term': '할인 계산', 'desc': '총액 × 0.9 = 10% 할인된 금액이에요.'}, {'term': 'int()', 'desc': '소수점 이하를 버리고 정수로 만들어요.'}], quizQ: '나이 3살이면 입장료는?', quizOpts: ['0원', '15,000원', '20,000원', '30,000원'], quizAns: 0, quizExplain: '4세 미만은 무료(영유아)!'),
  const ExItem(no: 'C08', title: '간단한 자판기', category: 'C', categoryName: '조건문', difficulty: '중급', hardware: '화면', type: 'text', description: '딕셔너리로 상품 목록을 만들고 구매를 시뮬레이션합니다.', pythonCode: "menu = {\n    1: ('콜라', 1500),\n    2: ('사이다', 1300),\n    3: ('주스', 2000),\n    4: ('물', 1000),\n}\n\nmoney = 3000\nchoice = 3\n\nprint('=== 자판기 ===')\nfor k, (name, price) in menu.items():\n    print(f'{k}. {name} ({price:,}원)')\n\nif choice in menu:\n    name, price = menu[choice]\n    if money >= price:\n        change = money - price\n        print(f'\\n{name} 구매! 거스름돈: {change:,}원')\n    else:\n        print(f'\\n잔액 부족! ({money:,}원 < {price:,}원)')\nelse:\n    print('없는 상품입니다.')", expectedOutput: "=== 자판기 ===\n1. 콜라 (1,500원)\n2. 사이다 (1,300원)\n3. 주스 (2,000원)\n4. 물 (1,000원)\n\n주스 구매! 거스름돈: 1,000원", steps: ['딕셔너리로 메뉴를 만듭니다', '선택한 상품의 가격을 확인합니다', '잔액이 충분하면 거스름돈을 계산합니다'], concepts: [{'term': '딕셔너리', 'desc': '번호:상품처럼 키와 값을 짝지어 저장하는 자료구조예요.'}, {'term': 'in menu', 'desc': '선택한 번호가 메뉴에 있는지 확인해요.'}, {'term': '튜플 언패킹', 'desc': "name, price = ('주스', 2000)처럼 한번에 꺼낼 수 있어요."}], quizQ: '딕셔너리에서 값을 꺼내는 방법은?', quizOpts: ['menu(1)', 'menu[1]', 'menu.1', 'menu{1}'], quizAns: 1, quizExplain: 'menu[키]로 값을 가져와요!'),
  const ExItem(no: 'C09', title: '교통 신호등', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '신호 색상에 따라 행동을 안내하는 시뮬레이터입니다.', pythonCode: "signals = ['빨강', '노랑', '초록']\n\nfor signal in signals:\n    print(f'현재 신호: {signal}')\n    if signal == '빨강':\n        print('  → 정지! 🔴')\n    elif signal == '노랑':\n        print('  → 주의! 🟡')\n    elif signal == '초록':\n        print('  → 출발! 🟢')\n    print()", expectedOutput: "현재 신호: 빨강\n  → 정지! 🔴\n\n현재 신호: 노랑\n  → 주의! 🟡\n\n현재 신호: 초록\n  → 출발! 🟢", steps: ['신호 색상 리스트를 만듭니다', '각 색상에 맞는 행동을 출력합니다', 'for문으로 모든 신호를 순서대로 처리합니다'], concepts: [{'term': '상태 기반 분기', 'desc': '현재 상태(신호 색)에 따라 다른 행동을 하는 패턴이에요.'}, {'term': 'for in 리스트', 'desc': '리스트의 요소를 하나씩 꺼내서 처리해요.'}, {'term': '== (문자열)', 'desc': "signal == '빨강'처럼 문자열도 비교할 수 있어요."}], quizQ: '노란 신호일 때 어떻게 해야 하나요?', quizOpts: ['출발', '정지', '주의', '후진'], quizAns: 2, quizExplain: '노란 신호는 주의! 멈출 준비를 해야 해요.'),
  const ExItem(no: 'C10', title: '가장 큰 수 찾기', category: 'C', categoryName: '조건문', difficulty: '기초', hardware: '화면', type: 'text', description: '세 숫자를 비교해서 가장 큰 수를 찾습니다.', pythonCode: "a, b, c = 42, 17, 58\n\nprint(f'세 수: {a}, {b}, {c}')\n\n# 방법 1: 조건문\nif a >= b and a >= c:\n    biggest = a\nelif b >= c:\n    biggest = b\nelse:\n    biggest = c\nprint(f'조건문: {biggest}')\n\n# 방법 2: max()\nprint(f'max(): {max(a, b, c)}')", expectedOutput: "세 수: 42, 17, 58\n조건문: 58\nmax(): 58", steps: ['세 숫자를 준비합니다', '조건문으로 비교해서 최대값을 찾습니다', 'max() 함수로도 같은 결과를 확인합니다'], concepts: [{'term': 'and 연산자', 'desc': 'a가 b보다 크고 c보다도 커야 최대값이에요.'}, {'term': 'max()', 'desc': '여러 값 중 가장 큰 값을 바로 반환하는 내장 함수예요.'}, {'term': '비교 연산', 'desc': '>=는 "크거나 같다"라는 뜻이에요.'}], quizQ: 'max(3, 7, 5)의 결과는?', quizOpts: ['3', '5', '7', '15'], quizAns: 2, quizExplain: 'max()는 가장 큰 값을 반환해요! 7이 제일 커요.'),

  // ═══════════════════════════════════════════
  //  D. 반복문 (기초~중급, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'D01', title: '1부터 100까지 합', category: 'D', categoryName: '반복문', difficulty: '기초', hardware: '화면', type: 'text', description: 'for문과 누적합으로 1부터 100까지의 합을 구합니다.', pythonCode: "total = 0\nfor i in range(1, 101):\n    total += i\n\nprint(f'1+2+3+...+100 = {total}')\nprint(f'공식 검증: {100*101//2}')", expectedOutput: "1+2+3+...+100 = 5050\n공식 검증: 5050", steps: ['total을 0으로 초기화합니다', 'for문으로 1~100까지 반복합니다', '각 숫자를 total에 더합니다'], concepts: [{'term': '+= (누적합)', 'desc': 'total += i는 total = total + i와 같아요.'}, {'term': 'range(1, 101)', 'desc': '1부터 100까지의 숫자를 생성해요.'}, {'term': '가우스 공식', 'desc': 'n까지의 합 = n(n+1)/2. 가우스가 어릴 때 발견했어요!'}], quizQ: '1부터 10까지의 합은?', quizOpts: ['45', '50', '55', '100'], quizAns: 2, quizExplain: '1+2+...+10 = 10×11÷2 = 55!'),
  const ExItem(no: 'D02', title: '카운트다운', category: 'D', categoryName: '반복문', difficulty: '기초', hardware: '화면', type: 'text', description: 'while문으로 10부터 1까지 카운트다운합니다.', pythonCode: "count = 10\nwhile count > 0:\n    print(f'{count}...')\n    count -= 1\n\nprint('발사! 🚀')", expectedOutput: "10...\n9...\n8...\n7...\n6...\n5...\n4...\n3...\n2...\n1...\n발사! 🚀", steps: ['count를 10으로 시작합니다', 'while로 0보다 큰 동안 반복합니다', '매번 1씩 줄입니다'], concepts: [{'term': 'while', 'desc': '조건이 참인 동안 계속 반복하는 명령이에요.'}, {'term': '-= 1', 'desc': 'count를 1씩 줄이는 표현이에요.'}, {'term': '종료 조건', 'desc': 'count가 0이 되면 while 조건이 거짓이 되어 멈춰요.'}], quizQ: 'while True는 언제 멈추나요?', quizOpts: ['1번 후', '10번 후', '영원히 안 멈춤', 'break할 때'], quizAns: 3, quizExplain: 'while True는 무한반복! break로만 탈출할 수 있어요.'),
  const ExItem(no: 'D03', title: '구구단 전체 출력', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: '이중 for문으로 2단부터 9단까지 전체 구구단을 출력합니다.', pythonCode: "for dan in range(2, 10):\n    print(f'--- {dan}단 ---')\n    for i in range(1, 10):\n        print(f'{dan}×{i}={dan*i:2d}', end='  ')\n    print()", expectedOutput: "--- 2단 ---\n2×1= 2  2×2= 4  2×3= 6  ...\n--- 3단 ---\n3×1= 3  ...", steps: ['바깥 for문으로 단(2~9)을 정합니다', '안쪽 for문으로 곱하는 수(1~9)를 정합니다', 'end=""로 같은 줄에 출력합니다'], concepts: [{'term': '이중 for문', 'desc': 'for 안에 for가 있으면 바깥×안쪽 횟수만큼 반복해요.'}, {'term': 'end=""', 'desc': 'print의 줄바꿈을 없애고 이어서 출력해요.'}, {'term': ':2d', 'desc': '숫자를 2자리로 맞춰 정렬해요.'}], quizQ: '이중 for문의 총 반복 횟수(2~9단)?', quizOpts: ['16번', '64번', '72번', '81번'], quizAns: 2, quizExplain: '8단 × 9줄 = 72번!'),
  const ExItem(no: 'D04', title: '다이아몬드 그리기', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: '별(*)로 다이아몬드 모양을 그립니다.', pythonCode: "n = 4\n# 윗부분\nfor i in range(1, n+1):\n    print(' '*(n-i) + '*'*(2*i-1))\n# 아랫부분\nfor i in range(n-1, 0, -1):\n    print(' '*(n-i) + '*'*(2*i-1))", expectedOutput: "   *\n  ***\n *****\n*******\n *****\n  ***\n   *", steps: ['윗부분: 별이 1,3,5,7개로 증가합니다', '아랫부분: 별이 5,3,1개로 감소합니다', '공백으로 가운데 정렬합니다'], concepts: [{'term': 'range(n,0,-1)', 'desc': 'n부터 1까지 역순으로 숫자를 만들어요.'}, {'term': '대칭 패턴', 'desc': '증가하는 부분과 감소하는 부분을 나눠 그려요.'}, {'term': '공백 계산', 'desc': '전체 너비 - 별 개수 = 앞의 공백 수'}], quizQ: 'range(5,0,-1)이 만드는 숫자는?', quizOpts: ['5,4,3,2,1', '5,4,3,2,1,0', '1,2,3,4,5', '0,1,2,3,4,5'], quizAns: 0, quizExplain: '5부터 시작해서 1씩 줄여 1까지! 0은 포함 안 돼요.'),
  const ExItem(no: 'D05', title: '숫자 뒤집기', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: 'while문과 나머지 연산으로 숫자를 뒤집습니다.', pythonCode: "num = 12345\noriginal = num\nreversed_num = 0\n\nwhile num > 0:\n    digit = num % 10\n    reversed_num = reversed_num * 10 + digit\n    num //= 10\n\nprint(f'{original} → {reversed_num}')", expectedOutput: "12345 → 54321", steps: ['% 10으로 마지막 자릿수를 꺼냅니다', '결과에 10을 곱하고 자릿수를 더합니다', '// 10으로 마지막 자릿수를 제거합니다'], concepts: [{'term': '% 10', 'desc': '10으로 나눈 나머지 = 일의 자리 숫자예요.'}, {'term': '// 10', 'desc': '10으로 나눈 몫 = 마지막 자릿수 제거예요.'}, {'term': '자릿수 조작', 'desc': '곱하기10+더하기로 자릿수를 쌓아올릴 수 있어요.'}], quizQ: '456 % 10의 결과는?', quizOpts: ['4', '45', '6', '56'], quizAns: 2, quizExplain: '456 ÷ 10 = 45...6이므로 나머지는 6!'),
  const ExItem(no: 'D06', title: '소수 목록 (1~50)', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: '이중 for문으로 1부터 50까지의 소수를 모두 찾습니다.', pythonCode: "primes = []\nfor num in range(2, 51):\n    is_prime = True\n    for i in range(2, int(num**0.5)+1):\n        if num % i == 0:\n            is_prime = False\n            break\n    if is_prime:\n        primes.append(num)\n\nprint(f'1~50 소수 ({len(primes)}개):')\nprint(primes)", expectedOutput: "1~50 소수 (15개):\n[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]", steps: ['2부터 50까지 각 숫자를 검사합니다', '√n까지 나누어보며 소수 여부를 판별합니다', '소수이면 리스트에 추가합니다'], concepts: [{'term': '이중 반복', 'desc': '바깥 for: 검사할 숫자, 안쪽 for: 나누는 수'}, {'term': 'break', 'desc': '나누어떨어지면 소수가 아니므로 즉시 중단!'}, {'term': '소수 판별', 'desc': '2부터 √n까지만 검사하면 충분해요.'}], quizQ: '1~10 소수는 몇 개?', quizOpts: ['3개', '4개', '5개', '6개'], quizAns: 1, quizExplain: '2, 3, 5, 7 총 4개! (1은 소수가 아니에요)'),
  const ExItem(no: 'D07', title: '체커보드 패턴', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: '이중 for문으로 체커보드(바둑판) 패턴을 출력합니다.', pythonCode: "size = 8\nfor row in range(size):\n    line = ''\n    for col in range(size):\n        if (row + col) % 2 == 0:\n            line += '■ '\n        else:\n            line += '□ '\n    print(line)", expectedOutput: "■ □ ■ □ ■ □ ■ □ \n□ ■ □ ■ □ ■ □ ■ \n■ □ ■ □ ■ □ ■ □ \n...", steps: ['8x8 크기로 반복합니다', '행+열의 합이 짝수면 ■, 홀수면 □', '각 줄을 문자열로 만들어 출력합니다'], concepts: [{'term': '(row+col)%2', 'desc': '행과 열의 합이 짝수/홀수로 번갈아 변해요.'}, {'term': '이중 for', 'desc': '바깥은 행, 안쪽은 열을 담당해요.'}, {'term': '문자열 누적', 'desc': "line += '■ '로 한 줄을 만들어가요."}], quizQ: '(2+3)%2의 결과는?', quizOpts: ['0', '1', '2', '5'], quizAns: 1, quizExplain: '2+3=5, 5÷2=2...1이므로 나머지 1! 홀수 칸이에요.'),
  const ExItem(no: 'D08', title: '구간 합 구하기', category: 'D', categoryName: '반복문', difficulty: '기초', hardware: '화면', type: 'text', description: '리스트에서 특정 구간의 합을 구합니다.', pythonCode: "nums = [3, 7, 2, 5, 8, 1, 4, 9, 6]\nstart, end = 2, 6  # 인덱스 2~5\n\nslice = nums[start:end]\ntotal = sum(slice)\n\nprint(f'전체: {nums}')\nprint(f'구간[{start}:{end}]: {slice}')\nprint(f'구간 합: {total}')", expectedOutput: "전체: [3, 7, 2, 5, 8, 1, 4, 9, 6]\n구간[2:6]: [2, 5, 8, 1]\n구간 합: 16", steps: ['숫자 리스트를 만듭니다', '슬라이싱으로 구간을 잘라냅니다', 'sum()으로 합을 구합니다'], concepts: [{'term': '슬라이싱 [a:b]', 'desc': '인덱스 a부터 b-1까지의 부분을 잘라내요.'}, {'term': 'sum()', 'desc': '리스트의 모든 값을 더해줘요.'}, {'term': '인덱스', 'desc': '리스트의 위치 번호예요. 0부터 시작!'}], quizQ: '[1,2,3,4,5][1:3]의 결과는?', quizOpts: ['[1,2,3]', '[2,3]', '[2,3,4]', '[1,2]'], quizAns: 1, quizExplain: '인덱스 1부터 2까지(3 미포함)이므로 [2,3]!'),
  const ExItem(no: 'D09', title: 'ASCII 아트', category: 'D', categoryName: '반복문', difficulty: '중급', hardware: '화면', type: 'text', description: '문자와 반복문으로 간단한 그림을 그립니다.', pythonCode: "# 하트 모양\nheart = [\n    '  ** **  ',\n    ' *******',\n    ' *******',\n    '  ***** ',\n    '   ***  ',\n    '    *   ',\n]\nfor line in heart:\n    print(line)\n\nprint()\n\n# 반복문으로 집 그리기\nfor i in range(5):\n    print(' '*(4-i) + '/'*(i+1) + '\\\\\\\\'*(i+1))\nfor i in range(4):\n    print('|' + ' '*8 + '|')\nprint('+' + '-'*8 + '+')", expectedOutput: "  ** **  \n *******\n *******\n  ***** \n   ***  \n    *   \n\n    /\\\n   //\\\\\n  ///\\\\\\\n ////\\\\\\\\\n/////\\\\\\\\\\\n|        |\n|        |\n|        |\n|        |\n+--------+", steps: ['리스트에 그림 한 줄씩 저장합니다', 'for문으로 한 줄씩 출력합니다', '문자열 반복(*)으로 패턴을 만듭니다'], concepts: [{'term': 'ASCII 아트', 'desc': '문자로 그림을 그리는 기법이에요.'}, {'term': '리스트 반복', 'desc': 'for line in heart로 각 줄을 순서대로 출력해요.'}, {'term': '이스케이프', 'desc': "\\\\는 역슬래시(\\) 하나를 표현해요."}], quizQ: "'#' * 5의 결과는?", quizOpts: ['#5', '#####', '# # # # #', '5'], quizAns: 1, quizExplain: "'#' * 5 = '#####' 문자열이 5번 반복돼요!"),
  const ExItem(no: 'D10', title: '숫자 야구 게임', category: 'D', categoryName: '반복문', difficulty: '고급', hardware: '화면', type: 'text', description: '3자리 비밀 숫자를 맞추는 숫자 야구 게임 시뮬레이션입니다.', pythonCode: "secret = '372'\nguesses = ['123', '357', '372']\n\nprint('=== 숫자 야구 ===')\nprint('3자리 숫자를 맞춰보세요!\\n')\n\nfor guess in guesses:\n    strike = sum(s == g for s, g in zip(secret, guess))\n    ball = sum(g in secret for g in guess) - strike\n    print(f'추측: {guess} → {strike}S {ball}B')\n    if strike == 3:\n        print('정답입니다! 🎉')\n        break", expectedOutput: "=== 숫자 야구 ===\n3자리 숫자를 맞춰보세요!\n\n추측: 123 → 0S 1B\n추측: 357 → 1S 1B\n추측: 372 → 3S 0B\n정답입니다! 🎉", steps: ['비밀 숫자 3자리를 정합니다', '추측과 비교하여 스트라이크/볼을 계산합니다', '3스트라이크면 정답!'], concepts: [{'term': '스트라이크', 'desc': '숫자와 위치 모두 맞으면 스트라이크!'}, {'term': '볼', 'desc': '숫자는 맞지만 위치가 다르면 볼!'}, {'term': 'zip()', 'desc': '두 리스트를 같은 위치끼리 묶어주는 함수예요.'}], quizQ: '비밀: 123, 추측: 132이면?', quizOpts: ['3S 0B', '1S 2B', '0S 3B', '2S 1B'], quizAns: 1, quizExplain: '1만 자리가 맞음(1S), 3과 2는 포함되지만 자리가 다름(2B)!'),

  // ═══════════════════════════════════════════
  //  E. 함수 (중급, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'E01', title: '인사 함수 만들기', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: 'def로 나만의 인사 함수를 만들고 호출합니다.', pythonCode: "def greet(name, msg='안녕하세요'):\n    print(f'{msg}, {name}님!')\n\ngreet('민수')\ngreet('영희', '반갑습니다')\ngreet('철수', '좋은 아침')", expectedOutput: "안녕하세요, 민수님!\n반갑습니다, 영희님!\n좋은 아침, 철수님!", steps: ['def로 함수를 정의합니다', '매개변수로 이름과 메시지를 받습니다', '기본값을 설정하면 생략 가능합니다'], concepts: [{'term': 'def', 'desc': '함수를 정의하는 키워드예요. def 함수이름(매개변수):'}, {'term': '매개변수', 'desc': '함수에 전달하는 값이에요. 호출할 때마다 달라질 수 있어요.'}, {'term': '기본값', 'desc': "msg='안녕하세요'처럼 생략하면 기본값이 사용돼요."}], quizQ: 'def greet(name)에서 name은?', quizOpts: ['변수', '매개변수', '함수', '클래스'], quizAns: 1, quizExplain: '함수에 전달되는 값을 매개변수(parameter)라고 해요!'),
  const ExItem(no: 'E02', title: '절대값 함수', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: 'return으로 값을 반환하는 절대값 함수를 만듭니다.', pythonCode: "def my_abs(x):\n    if x < 0:\n        return -x\n    return x\n\nnums = [-5, 3, -1, 0, -8]\nfor n in nums:\n    print(f'my_abs({n}) = {my_abs(n)}')", expectedOutput: "my_abs(-5) = 5\nmy_abs(3) = 3\nmy_abs(-1) = 1\nmy_abs(0) = 0\nmy_abs(-8) = 8", steps: ['함수에서 음수면 부호를 바꿉니다', 'return으로 결과를 반환합니다', '여러 숫자로 테스트합니다'], concepts: [{'term': 'return', 'desc': '함수의 결과를 돌려주는 명령이에요. 함수가 끝나요.'}, {'term': '절대값', 'desc': '숫자의 부호를 없앤 값이에요. |-5| = 5'}, {'term': '조건 반환', 'desc': '조건에 따라 다른 값을 return할 수 있어요.'}], quizQ: 'return의 역할은?', quizOpts: ['출력', '값 반환', '반복', '입력'], quizAns: 1, quizExplain: 'return은 함수의 결과를 호출한 곳으로 돌려줘요!'),
  const ExItem(no: 'E03', title: '최대값 함수 (*args)', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '*args로 개수가 정해지지 않은 인자를 받는 함수를 만듭니다.', pythonCode: "def my_max(*args):\n    result = args[0]\n    for val in args[1:]:\n        if val > result:\n            result = val\n    return result\n\nprint(my_max(3, 7, 1))\nprint(my_max(10, 20, 5, 15))\nprint(my_max(42))", expectedOutput: "7\n20\n42", steps: ['*args로 여러 값을 받습니다', '첫 번째 값을 최대로 가정합니다', '나머지와 비교하여 더 큰 값으로 교체합니다'], concepts: [{'term': '*args', 'desc': '개수가 정해지지 않은 여러 인자를 튜플로 받아요.'}, {'term': 'args[1:]', 'desc': '첫 번째를 제외한 나머지 요소를 슬라이싱해요.'}, {'term': '비교 갱신', 'desc': '더 큰 값을 발견하면 result를 갱신해요.'}], quizQ: 'def f(*args)에서 f(1,2,3) 호출 시 args는?', quizOpts: ['[1,2,3]', '(1,2,3)', '{1,2,3}', '1'], quizAns: 1, quizExplain: '*args는 튜플로 받아요! (1, 2, 3)'),
  const ExItem(no: 'E04', title: '온도 변환 함수', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '섭씨↔화씨 변환 함수 2개를 만들어 사용합니다.', pythonCode: "def to_fahrenheit(c):\n    return c * 9/5 + 32\n\ndef to_celsius(f):\n    return (f - 32) * 5/9\n\ntemps_c = [0, 20, 36.5, 100]\nfor c in temps_c:\n    f = to_fahrenheit(c)\n    print(f'{c}°C = {f:.1f}°F')\n\nprint(f'\\n98.6°F = {to_celsius(98.6):.1f}°C')", expectedOutput: "0°C = 32.0°F\n20°C = 68.0°F\n36.5°C = 97.7°F\n100°C = 212.0°F\n\n98.6°F = 37.0°C", steps: ['두 개의 변환 함수를 만듭니다', '여러 온도를 변환합니다', ':.1f로 소수점 1자리 표시'], concepts: [{'term': '함수 분리', 'desc': '각 변환을 별도 함수로 만들면 재사용이 쉬워요.'}, {'term': '반환값 활용', 'desc': 'f = to_fahrenheit(c)처럼 반환값을 변수에 저장해요.'}, {'term': '함수 호출', 'desc': '함수이름(인자)로 호출하면 결과가 반환돼요.'}], quizQ: '0°C는 화씨 몇 도?', quizOpts: ['0°F', '32°F', '100°F', '-40°F'], quizAns: 1, quizExplain: '0 × 9/5 + 32 = 32°F! 물이 어는 온도예요.'),
  const ExItem(no: 'E05', title: '재귀로 팩토리얼', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '함수가 자기 자신을 호출하는 재귀로 팩토리얼을 구합니다.', pythonCode: "def factorial(n):\n    if n <= 1:  # 종료 조건\n        return 1\n    return n * factorial(n - 1)\n\nfor i in range(1, 8):\n    print(f'{i}! = {factorial(i)}')", expectedOutput: "1! = 1\n2! = 2\n3! = 6\n4! = 24\n5! = 120\n6! = 720\n7! = 5040", steps: ['n이 1 이하면 1을 반환합니다 (종료 조건)', 'n × factorial(n-1)로 자기 자신을 호출합니다', '5! = 5×4×3×2×1 순서로 계산됩니다'], concepts: [{'term': '재귀', 'desc': '함수가 자기 자신을 호출하는 기법이에요.'}, {'term': '종료 조건', 'desc': '재귀가 무한히 반복되지 않도록 멈추는 조건이에요.'}, {'term': '호출 스택', 'desc': 'f(5)→f(4)→f(3)→...→f(1) 순서로 쌓였다가 돌아와요.'}], quizQ: '재귀에서 종료 조건이 없으면?', quizOpts: ['정상 작동', '무한 반복 에러', '0 반환', '자동 종료'], quizAns: 1, quizExplain: '종료 조건이 없으면 무한히 호출되다가 에러(RecursionError)!'),
  const ExItem(no: 'E06', title: '피보나치 함수', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '재귀와 반복 두 가지 방법으로 피보나치를 구현합니다.', pythonCode: "# 방법 1: 반복\ndef fib_loop(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n\n# 방법 2: 재귀\ndef fib_rec(n):\n    if n <= 1: return n\n    return fib_rec(n-1) + fib_rec(n-2)\n\nfor i in range(10):\n    print(f'F({i}) = {fib_loop(i)}')", expectedOutput: "F(0) = 0\nF(1) = 1\nF(2) = 1\nF(3) = 2\nF(4) = 3\nF(5) = 5\nF(6) = 8\nF(7) = 13\nF(8) = 21\nF(9) = 34", steps: ['반복 방식: a,b를 교대로 업데이트합니다', '재귀 방식: f(n)=f(n-1)+f(n-2)로 호출합니다', '두 방법 모두 같은 결과를 줍니다'], concepts: [{'term': '반복 vs 재귀', 'desc': '같은 문제를 for문 또는 자기호출로 풀 수 있어요.'}, {'term': '효율성', 'desc': '반복이 재귀보다 빨라요. 재귀는 같은 계산을 반복하기도 해요.'}, {'term': 'a, b = b, a+b', 'desc': '동시 대입으로 두 변수를 한번에 업데이트해요.'}], quizQ: 'fib(6)의 값은?', quizOpts: ['5', '8', '13', '6'], quizAns: 1, quizExplain: 'F(6) = F(5)+F(4) = 5+3 = 8!'),
  const ExItem(no: 'E07', title: '람다와 정렬', category: 'E', categoryName: '함수', difficulty: '고급', hardware: '화면', type: 'text', description: 'lambda로 짧은 함수를 만들고 정렬에 활용합니다.', pythonCode: "# 기본 람다\nsquare = lambda x: x ** 2\nprint(f'square(5) = {square(5)}')\n\n# 정렬에 활용\nstudents = [('민수', 85), ('영희', 92), ('철수', 78)]\nby_score = sorted(students, key=lambda s: s[1])\nby_name = sorted(students, key=lambda s: s[0])\n\nprint(f'점수순: {by_score}')\nprint(f'이름순: {by_name}')", expectedOutput: "square(5) = 25\n점수순: [('철수', 78), ('민수', 85), ('영희', 92)]\n이름순: [('민수', 85), ('영희', 92), ('철수', 78)]", steps: ['lambda로 한 줄 함수를 만듭니다', 'sorted의 key에 lambda를 전달합니다', '다양한 기준으로 정렬할 수 있습니다'], concepts: [{'term': 'lambda', 'desc': 'lambda x: x**2는 def f(x): return x**2와 같아요.'}, {'term': 'sorted(key=)', 'desc': 'key에 함수를 주면 그 기준으로 정렬해요.'}, {'term': '튜플 인덱싱', 'desc': "('민수', 85)[1] = 85. 두 번째 요소를 꺼내요."}], quizQ: 'lambda x: x*2에 3을 넣으면?', quizOpts: ['2', '3', '6', '32'], quizAns: 2, quizExplain: 'lambda x: x*2는 x를 2배하는 함수! 3*2=6'),
  const ExItem(no: 'E08', title: '데코레이터 맛보기', category: 'E', categoryName: '함수', difficulty: '고급', hardware: '화면', type: 'text', description: '함수를 감싸는 함수(데코레이터)로 기능을 추가합니다.', pythonCode: "import time\n\ndef timer(func):\n    def wrapper(*args):\n        start = time.time()\n        result = func(*args)\n        elapsed = time.time() - start\n        print(f'  ({elapsed:.4f}초 걸림)')\n        return result\n    return wrapper\n\n@timer\ndef slow_add(a, b):\n    total = 0\n    for _ in range(1000000):\n        total += 1\n    return a + b\n\nresult = slow_add(3, 5)\nprint(f'결과: {result}')", expectedOutput: "  (0.0500초 걸림)\n결과: 8", steps: ['timer 데코레이터 함수를 정의합니다', '@timer를 함수 위에 붙입니다', '함수 실행 시간이 자동으로 측정됩니다'], concepts: [{'term': '데코레이터', 'desc': '함수를 감싸서 추가 기능(시간 측정 등)을 붙여요.'}, {'term': '@', 'desc': "@timer는 slow_add = timer(slow_add)와 같아요."}, {'term': 'wrapper', 'desc': '원래 함수를 감싸는 내부 함수예요.'}], quizQ: '데코레이터의 역할은?', quizOpts: ['함수 삭제', '함수에 기능 추가', '변수 선언', '클래스 생성'], quizAns: 1, quizExplain: '데코레이터는 기존 함수를 수정하지 않고 기능을 추가해요!'),
  const ExItem(no: 'E09', title: '함수로 계산기', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '딕셔너리에 함수를 매핑하여 계산기를 만듭니다.', pythonCode: "def add(a, b): return a + b\ndef sub(a, b): return a - b\ndef mul(a, b): return a * b\ndef div(a, b): return a / b if b != 0 else '에러'\n\nops = {'+': add, '-': sub, '*': mul, '/': div}\n\ntests = [(10, '+', 3), (10, '-', 3), (10, '*', 3), (10, '/', 3)]\nfor a, op, b in tests:\n    result = ops[op](a, b)\n    print(f'{a} {op} {b} = {result}')", expectedOutput: "10 + 3 = 13\n10 - 3 = 7\n10 * 3 = 30\n10 / 3 = 3.3333333333333335", steps: ['사칙연산 함수 4개를 만듭니다', '딕셔너리로 연산자와 함수를 매핑합니다', '연산자로 해당 함수를 호출합니다'], concepts: [{'term': '함수 매핑', 'desc': '딕셔너리에 함수를 값으로 저장할 수 있어요.'}, {'term': 'ops[op](a,b)', 'desc': "ops['+']는 add 함수이므로, add(10,3)이 호출돼요."}, {'term': '0 나누기 방지', 'desc': 'b가 0이면 에러가 나므로 미리 검사해요.'}], quizQ: "ops = {'+': add}일 때 ops['+'](2,3)은?", quizOpts: ['에러', '23', '5', "'+'"  ], quizAns: 2, quizExplain: "ops['+']는 add 함수! add(2,3) = 5"),
  const ExItem(no: 'E10', title: '기본값 매개변수', category: 'E', categoryName: '함수', difficulty: '중급', hardware: '화면', type: 'text', description: '기본값이 있는 매개변수로 유연한 함수를 만듭니다.', pythonCode: "def introduce(name, age=None, city='서울'):\n    msg = f'이름: {name}'\n    if age:\n        msg += f', 나이: {age}살'\n    msg += f', 도시: {city}'\n    print(msg)\n\nintroduce('민수')\nintroduce('영희', 15)\nintroduce('철수', 14, '부산')\nintroduce('지영', city='대전')", expectedOutput: "이름: 민수, 도시: 서울\n이름: 영희, 나이: 15살, 도시: 서울\n이름: 철수, 나이: 14살, 도시: 부산\n이름: 지영, 도시: 대전", steps: ['기본값이 있는 매개변수를 정의합니다', '생략하면 기본값이 사용됩니다', '키워드 인자로 특정 값만 전달할 수 있습니다'], concepts: [{'term': '기본값 매개변수', 'desc': "city='서울'처럼 기본값을 정하면 생략 가능해요."}, {'term': '키워드 인자', 'desc': "city='대전'처럼 이름을 지정해서 전달해요."}, {'term': 'None', 'desc': "'값이 없음'을 나타내는 특별한 값이에요."}], quizQ: "def f(a, b=10)에서 f(5)의 b값은?", quizOpts: ['5', '10', 'None', '에러'], quizAns: 1, quizExplain: 'b를 생략했으므로 기본값 10이 사용돼요!'),

  // ═══════════════════════════════════════════
  //  F. 문자열 (중급, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'F01', title: '문자열 뒤집기', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '슬라이싱으로 문자열을 뒤집습니다.', pythonCode: "text = 'Hello Python'\nreversed_text = text[::-1]\n\nprint(f'원본: {text}')\nprint(f'뒤집기: {reversed_text}')\n\n# 단어별 뒤집기\nwords = text.split()\nreversed_words = ' '.join(words[::-1])\nprint(f'단어 뒤집기: {reversed_words}')", expectedOutput: "원본: Hello Python\n뒤집기: nohtyP olleH\n단어 뒤집기: Python Hello", steps: ['[::-1]로 전체를 뒤집습니다', 'split()으로 단어를 나눕니다', '단어 순서만 뒤집을 수도 있습니다'], concepts: [{'term': '[::-1]', 'desc': '슬라이싱의 step이 -1이면 역순으로 읽어요.'}, {'term': 'split()', 'desc': '공백 기준으로 문자열을 나눠 리스트로 만들어요.'}, {'term': "join()", 'desc': "리스트를 하나의 문자열로 합쳐요. ' '.join(['a','b']) = 'a b'"}], quizQ: "'abc'[::-1]의 결과는?", quizOpts: ['abc', 'cba', 'a', 'error'], quizAns: 1, quizExplain: '[::-1]은 문자열을 뒤집어요! abc → cba'),
  const ExItem(no: 'F02', title: '회문(팰린드롬) 판별', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '앞으로 읽어도 뒤로 읽어도 같은 단어인지 판별합니다.', pythonCode: "words = ['level', 'hello', 'radar', 'python', '토마토']\n\nfor word in words:\n    cleaned = word.lower()\n    is_palindrome = cleaned == cleaned[::-1]\n    mark = '⭕' if is_palindrome else '❌'\n    print(f'{mark} {word}')", expectedOutput: "⭕ level\n❌ hello\n⭕ radar\n❌ python\n⭕ 토마토", steps: ['단어를 소문자로 통일합니다', '원본과 뒤집은 것을 비교합니다', '같으면 회문(팰린드롬)입니다'], concepts: [{'term': '회문', 'desc': 'level, 토마토처럼 앞뒤로 읽어도 같은 단어예요.'}, {'term': '.lower()', 'desc': '대문자를 모두 소문자로 바꿔서 비교를 쉽게 해요.'}, {'term': '[::-1]', 'desc': '문자열을 뒤집어서 원본과 비교해요.'}], quizQ: "'abba'는 회문인가요?", quizOpts: ['예', '아니오', '알 수 없음', '에러'], quizAns: 0, quizExplain: "abba를 뒤집으면 abba! 같으므로 회문이에요!"),
  const ExItem(no: 'F03', title: '단어 개수 세기', category: 'F', categoryName: '문자열', difficulty: '기초', hardware: '화면', type: 'text', description: 'split()으로 문장의 단어 수를 세고 분석합니다.', pythonCode: "text = 'Python은 쉽고 재미있는 프로그래밍 언어입니다'\n\nwords = text.split()\nprint(f'문장: {text}')\nprint(f'단어 수: {len(words)}')\nprint(f'글자 수: {len(text)}')\nprint(f'공백 제외: {len(text.replace(\" \", \"\"))}')\n\nfor i, w in enumerate(words, 1):\n    print(f'  {i}. {w}')", expectedOutput: "문장: Python은 쉽고 재미있는 프로그래밍 언어입니다\n단어 수: 5\n글자 수: 26\n공백 제외: 22\n  1. Python은\n  2. 쉽고\n  3. 재미있는\n  4. 프로그래밍\n  5. 언어입니다", steps: ['split()으로 단어를 나눕니다', 'len()으로 단어/글자 수를 셉니다', 'enumerate()로 번호를 매깁니다'], concepts: [{'term': 'split()', 'desc': '공백 기준으로 문자열을 나눠 리스트로 만들어요.'}, {'term': 'len()', 'desc': '문자열 길이 또는 리스트 요소 수를 알려줘요.'}, {'term': 'enumerate()', 'desc': '반복 시 인덱스 번호를 함께 제공해요.'}], quizQ: "'a b c'.split()의 결과는?", quizOpts: ["'abc'", "['a','b','c']", "['a b c']", "3"], quizAns: 1, quizExplain: "split()은 공백으로 나누어 리스트를 만들어요!"),
  const ExItem(no: 'F04', title: '대소문자 변환', category: 'F', categoryName: '문자열', difficulty: '기초', hardware: '화면', type: 'text', description: '문자열의 대소문자를 다양하게 변환합니다.', pythonCode: "text = 'Hello Python World'\n\nprint(f'원본: {text}')\nprint(f'대문자: {text.upper()}')\nprint(f'소문자: {text.lower()}')\nprint(f'제목형: {text.title()}')\nprint(f'뒤집기: {text.swapcase()}')\nprint(f'첫글자만: {text.capitalize()}')", expectedOutput: "원본: Hello Python World\n대문자: HELLO PYTHON WORLD\n소문자: hello python world\n제목형: Hello Python World\n뒤집기: hELLO pYTHON wORLD\n첫글자만: Hello python world", steps: ['원본 문자열을 준비합니다', '다양한 메서드로 변환합니다', '각 메서드의 결과를 비교합니다'], concepts: [{'term': '.upper()', 'desc': '모든 글자를 대문자로 바꿔요.'}, {'term': '.lower()', 'desc': '모든 글자를 소문자로 바꿔요.'}, {'term': '.swapcase()', 'desc': '대문자↔소문자를 서로 뒤바꿔요.'}], quizQ: "'Hello'.swapcase()의 결과는?", quizOpts: ['HELLO', 'hello', 'hELLO', 'Hello'], quizAns: 2, quizExplain: 'swapcase는 대소문자를 뒤집어요! H→h, ello→ELLO'),
  const ExItem(no: 'F05', title: '문자 빈도수 세기', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '문자열에서 각 문자가 몇 번 나오는지 셉니다.', pythonCode: "text = 'banana'\ncounts = {}\n\nfor ch in text:\n    counts[ch] = counts.get(ch, 0) + 1\n\nprint(f'문자열: {text}')\nfor ch, cnt in sorted(counts.items()):\n    bar = '█' * cnt\n    print(f'  {ch}: {cnt}번 {bar}')", expectedOutput: "문자열: banana\n  a: 3번 ███\n  b: 1번 █\n  n: 2번 ██", steps: ['각 문자를 하나씩 검사합니다', '딕셔너리에 빈도수를 기록합니다', '정렬하여 결과를 막대그래프로 표시합니다'], concepts: [{'term': 'dict.get(key, 0)', 'desc': '키가 없으면 0을 반환하는 안전한 방법이에요.'}, {'term': '딕셔너리 카운팅', 'desc': '각 문자를 키로, 횟수를 값으로 저장해요.'}, {'term': 'sorted()', 'desc': '딕셔너리를 정렬된 순서로 출력해요.'}], quizQ: "'aab'에서 'a'의 빈도수는?", quizOpts: ['1', '2', '3', '0'], quizAns: 1, quizExplain: "'aab'에서 a는 2번 나와요!"),
  const ExItem(no: 'F06', title: '숫자만 추출하기', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '문자열에서 숫자만 골라내는 방법을 배웁니다.', pythonCode: "text = '전화번호: 010-1234-5678, 나이: 15세'\n\n# 방법 1: for + isdigit\ndigits = ''\nfor ch in text:\n    if ch.isdigit():\n        digits += ch\nprint(f'숫자만: {digits}')\n\n# 방법 2: 리스트 컴프리헨션\ndigits2 = ''.join([ch for ch in text if ch.isdigit()])\nprint(f'같은 결과: {digits2}')", expectedOutput: "숫자만: 01012345678155\n같은 결과: 01012345678155", steps: ['문자열을 한 글자씩 검사합니다', 'isdigit()으로 숫자인지 판별합니다', '숫자만 모아서 새 문자열을 만듭니다'], concepts: [{'term': '.isdigit()', 'desc': '문자가 숫자(0~9)인지 확인하는 메서드예요.'}, {'term': '필터링', 'desc': '조건에 맞는 것만 골라내는 기법이에요.'}, {'term': '컴프리헨션', 'desc': '[ch for ch in text if 조건]으로 간결하게 필터링해요.'}], quizQ: "'3'.isdigit()의 결과는?", quizOpts: ['True', 'False', '3', "'3'"], quizAns: 0, quizExplain: "'3'은 숫자 문자이므로 isdigit()은 True!"),
  const ExItem(no: 'F07', title: '시저 암호', category: 'F', categoryName: '문자열', difficulty: '고급', hardware: '화면', type: 'text', description: '알파벳을 일정 칸수만큼 밀어서 암호화합니다.', pythonCode: "def caesar(text, shift):\n    result = ''\n    for ch in text:\n        if ch.isalpha():\n            base = ord('A') if ch.isupper() else ord('a')\n            result += chr((ord(ch) - base + shift) % 26 + base)\n        else:\n            result += ch\n    return result\n\nplain = 'Hello World'\nshift = 3\nencrypted = caesar(plain, shift)\ndecrypted = caesar(encrypted, -shift)\n\nprint(f'원문: {plain}')\nprint(f'암호화(+{shift}): {encrypted}')\nprint(f'복호화: {decrypted}')", expectedOutput: "원문: Hello World\n암호화(+3): Khoor Zruog\n복호화: Hello World", steps: ['각 알파벳을 shift만큼 이동합니다', 'ord()로 아스키 코드를 얻고 chr()로 되돌립니다', '% 26으로 z 이후에 a로 순환합니다'], concepts: [{'term': 'ord()', 'desc': "문자의 아스키 코드를 반환해요. ord('A')=65"}, {'term': 'chr()', 'desc': "아스키 코드를 문자로 바꿔요. chr(65)='A'"}, {'term': '% 26', 'desc': '알파벳 26자를 순환하기 위한 나머지 연산이에요.'}], quizQ: "'A'를 3칸 밀면?", quizOpts: ['B', 'C', 'D', 'E'], quizAns: 2, quizExplain: 'A→B→C→D! 3칸 밀면 D가 돼요.'),
  const ExItem(no: 'F08', title: '이메일 검증', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '간단한 규칙으로 이메일 주소의 유효성을 검사합니다.', pythonCode: "def check_email(email):\n    if '@' not in email:\n        return '@ 없음'\n    if '.' not in email.split('@')[1]:\n        return '도메인에 . 없음'\n    if email.count('@') > 1:\n        return '@ 여러 개'\n    if len(email.split('@')[0]) < 1:\n        return '아이디 없음'\n    return '유효'\n\nemails = ['user@gmail.com', 'bad-email', 'no@dot', 'a@@b.c']\nfor e in emails:\n    print(f'{e:20s} → {check_email(e)}')", expectedOutput: "user@gmail.com       → 유효\nbad-email            → @ 없음\nno@dot               → 도메인에 . 없음\na@@b.c               → @ 여러 개", steps: ['@가 있는지 확인합니다', '도메인에 .이 있는지 확인합니다', '각 조건을 순서대로 검사합니다'], concepts: [{'term': "'@' in email", 'desc': '문자열 안에 특정 문자가 있는지 검사해요.'}, {'term': '.split("@")', 'desc': "'@' 기준으로 아이디와 도메인을 분리해요."}, {'term': '.count()', 'desc': '특정 문자가 몇 번 나오는지 세요.'}], quizQ: "'hello'.count('l')의 결과는?", quizOpts: ['1', '2', '3', '0'], quizAns: 1, quizExplain: "'hello'에서 'l'은 2번 나와요!"),
  const ExItem(no: 'F09', title: '문자열 압축', category: 'F', categoryName: '문자열', difficulty: '고급', hardware: '화면', type: 'text', description: '연속된 같은 문자를 개수+문자로 압축합니다.', pythonCode: "def compress(text):\n    if not text: return ''\n    result = ''\n    count = 1\n    for i in range(1, len(text)):\n        if text[i] == text[i-1]:\n            count += 1\n        else:\n            result += f'{count}{text[i-1]}'\n            count = 1\n    result += f'{count}{text[-1]}'\n    return result\n\ntests = ['aaabbbcc', 'aabbcc', 'abcd']\nfor t in tests:\n    print(f'{t} → {compress(t)}')", expectedOutput: "aaabbbcc → 3a3b2c\naabbcc → 2a2b2c\nabcd → 1a1b1c1d", steps: ['연속된 같은 문자의 개수를 셉니다', '다른 문자가 나오면 개수+문자를 저장합니다', '마지막 문자도 처리합니다'], concepts: [{'term': '연속 카운트', 'desc': '같은 문자가 연속으로 몇 번 나오는지 세는 기법이에요.'}, {'term': 'text[i-1]', 'desc': '이전 문자와 비교하여 같은지 확인해요.'}, {'term': 'text[-1]', 'desc': '마지막 문자를 가리키는 인덱스예요.'}], quizQ: "'aaa'를 압축하면?", quizOpts: ['a3', '3a', 'aaa', '1a1a1a'], quizAns: 1, quizExplain: 'a가 3번 연속이므로 3a!'),
  const ExItem(no: 'F10', title: '애너그램 판별', category: 'F', categoryName: '문자열', difficulty: '중급', hardware: '화면', type: 'text', description: '두 단어가 같은 글자로 이루어진 애너그램인지 판별합니다.', pythonCode: "def is_anagram(a, b):\n    return sorted(a.lower()) == sorted(b.lower())\n\npairs = [('listen', 'silent'), ('hello', 'world'), ('tea', 'eat')]\nfor a, b in pairs:\n    result = '⭕' if is_anagram(a, b) else '❌'\n    print(f'{result} {a} ↔ {b}')", expectedOutput: "⭕ listen ↔ silent\n❌ hello ↔ world\n⭕ tea ↔ eat", steps: ['두 단어를 소문자로 바꿉니다', 'sorted()로 글자를 정렬합니다', '정렬 결과가 같으면 애너그램입니다'], concepts: [{'term': '애너그램', 'desc': '같은 글자를 재배열한 단어예요. listen ↔ silent'}, {'term': 'sorted()', 'desc': '문자열을 글자 단위로 정렬한 리스트를 반환해요.'}, {'term': '.lower()', 'desc': '대소문자 구분 없이 비교하기 위해 소문자로 통일해요.'}], quizQ: "'abc'와 'cba'는 애너그램?", quizOpts: ['예', '아니오', '알 수 없음', '에러'], quizAns: 0, quizExplain: "sorted('abc')=['a','b','c'], sorted('cba')=['a','b','c']. 같으므로 애너그램!"),

  // ═══════════════════════════════════════════
  //  G. 리스트/딕셔너리 (중급, 화면, text)
  // ═══════════════════════════════════════════
  const ExItem(no: 'G01', title: '리스트 기본 조작', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '리스트에 요소를 추가, 삭제, 정렬하는 기본 조작을 배웁니다.', pythonCode: "fruits = ['사과', '바나나', '딸기']\nprint(f'원본: {fruits}')\n\nfruits.append('포도')\nprint(f'추가: {fruits}')\n\nfruits.remove('바나나')\nprint(f'삭제: {fruits}')\n\nfruits.sort()\nprint(f'정렬: {fruits}')\n\nprint(f'개수: {len(fruits)}')\nprint(f'첫번째: {fruits[0]}')\nprint(f'마지막: {fruits[-1]}')", expectedOutput: "원본: ['사과', '바나나', '딸기']\n추가: ['사과', '바나나', '딸기', '포도']\n삭제: ['사과', '딸기', '포도']\n정렬: ['딸기', '사과', '포도']\n개수: 3\n첫번째: 딸기\n마지막: 포도", steps: ['append()로 요소를 추가합니다', 'remove()로 요소를 삭제합니다', 'sort()로 정렬합니다'], concepts: [{'term': '.append()', 'desc': '리스트 끝에 새 요소를 추가해요.'}, {'term': '.remove()', 'desc': '지정한 값을 찾아서 삭제해요.'}, {'term': '인덱스 [-1]', 'desc': '-1은 마지막 요소를 가리켜요.'}], quizQ: '[1,2,3].append(4)의 결과는?', quizOpts: ['[1,2,3,4]', '[4,1,2,3]', '[1,2,3]', '4'], quizAns: 0, quizExplain: 'append는 끝에 추가! [1,2,3,4]가 돼요.'),
  const ExItem(no: 'G02', title: '리스트 컴프리헨션', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '한 줄로 리스트를 생성하는 컴프리헨션을 배웁니다.', pythonCode: "# 1~10 제곱\nsquares = [x**2 for x in range(1, 11)]\nprint(f'제곱: {squares}')\n\n# 짝수만\nevens = [x for x in range(1, 21) if x % 2 == 0]\nprint(f'짝수: {evens}')\n\n# 문자열 변환\nwords = ['hello', 'python', 'world']\nupper = [w.upper() for w in words]\nprint(f'대문자: {upper}')", expectedOutput: "제곱: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]\n짝수: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]\n대문자: ['HELLO', 'PYTHON', 'WORLD']", steps: ['[표현식 for 변수 in 범위]로 리스트를 만듭니다', 'if 조건을 추가하여 필터링합니다', '다양한 변환을 적용할 수 있습니다'], concepts: [{'term': '컴프리헨션', 'desc': '[x**2 for x in range(10)]처럼 한 줄로 리스트를 생성해요.'}, {'term': '조건 필터', 'desc': 'if x%2==0을 추가하면 짝수만 골라요.'}, {'term': '변환 적용', 'desc': 'w.upper()처럼 각 요소에 함수를 적용할 수 있어요.'}], quizQ: '[x*2 for x in [1,2,3]]의 결과는?', quizOpts: ['[1,2,3]', '[2,4,6]', '[1,4,9]', '6'], quizAns: 1, quizExplain: '각 요소에 *2를 적용! [2,4,6]'),
  const ExItem(no: 'G03', title: '2차원 리스트 (행렬)', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '리스트 안의 리스트로 행렬(표)을 표현합니다.', pythonCode: "matrix = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9]\n]\n\nprint('행렬:')\nfor row in matrix:\n    print(row)\n\nprint(f'\\n(1,2) = {matrix[1][2]}')\nprint(f'대각선: {matrix[0][0]}, {matrix[1][1]}, {matrix[2][2]}')", expectedOutput: "행렬:\n[1, 2, 3]\n[4, 5, 6]\n[7, 8, 9]\n\n(1,2) = 6\n대각선: 1, 5, 9", steps: ['리스트 안에 리스트를 넣어 2차원을 만듭니다', 'matrix[행][열]로 특정 요소에 접근합니다', '대각선 요소를 출력합니다'], concepts: [{'term': '2차원 리스트', 'desc': '리스트 안에 리스트! 행과 열이 있는 표예요.'}, {'term': 'matrix[1][2]', 'desc': '1번째 행, 2번째 열의 값을 가져와요. (0부터 시작)'}, {'term': '대각선', 'desc': '행과 열 인덱스가 같은 요소들이에요.'}], quizQ: 'matrix[0][1]의 값은? (위 코드)', quizOpts: ['1', '2', '4', '5'], quizAns: 1, quizExplain: '0번째 행[1,2,3]의 1번째 요소 = 2!'),
  const ExItem(no: 'G04', title: '딕셔너리 전화번호부', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '딕셔너리로 전화번호부를 만들고 검색합니다.', pythonCode: "phonebook = {\n    '민수': '010-1234-5678',\n    '영희': '010-2345-6789',\n    '철수': '010-3456-7890',\n}\n\nprint('=== 전화번호부 ===')\nfor name, phone in phonebook.items():\n    print(f'  {name}: {phone}')\n\nsearch = '영희'\nif search in phonebook:\n    print(f'\\n{search}: {phonebook[search]}')\nelse:\n    print(f'\\n{search}을(를) 찾을 수 없습니다.')", expectedOutput: "=== 전화번호부 ===\n  민수: 010-1234-5678\n  영희: 010-2345-6789\n  철수: 010-3456-7890\n\n영희: 010-2345-6789", steps: ['이름:번호 딕셔너리를 만듭니다', '.items()로 모든 항목을 출력합니다', 'in으로 검색하여 번호를 찾습니다'], concepts: [{'term': '딕셔너리', 'desc': '{키: 값} 형태로 데이터를 저장해요.'}, {'term': '.items()', 'desc': '키와 값을 함께 가져와요.'}, {'term': "key in dict", 'desc': '딕셔너리에 해당 키가 있는지 확인해요.'}], quizQ: "dict = {'a': 1}일 때 dict['a']는?", quizOpts: ['a', '1', "{'a': 1}", 'error'], quizAns: 1, quizExplain: '키 "a"에 해당하는 값 1을 반환해요!'),
  const ExItem(no: 'G05', title: '학생 성적 관리', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '딕셔너리 리스트로 학생 성적을 관리합니다.', pythonCode: "students = [\n    {'name': '민수', 'kor': 85, 'math': 92},\n    {'name': '영희', 'kor': 78, 'math': 95},\n    {'name': '철수', 'kor': 92, 'math': 88},\n]\n\nprint('이름   국어  수학  평균')\nprint('-' * 25)\nfor s in students:\n    avg = (s['kor'] + s['math']) / 2\n    print(f\"{s['name']:4s} {s['kor']:5d} {s['math']:5d} {avg:5.1f}\")\n\nkor_avg = sum(s['kor'] for s in students) / len(students)\nprint(f'\\n국어 평균: {kor_avg:.1f}')", expectedOutput: "이름   국어  수학  평균\n-------------------------\n민수      85    92  88.5\n영희      78    95  86.5\n철수      92    88  90.0\n\n국어 평균: 85.0", steps: ['딕셔너리 리스트로 학생 데이터를 만듭니다', '각 학생의 평균을 계산합니다', '전체 국어 평균도 구합니다'], concepts: [{'term': '딕셔너리 리스트', 'desc': '[{...}, {...}] 형태로 여러 레코드를 관리해요.'}, {'term': "s['kor']", 'desc': '딕셔너리에서 과목 점수를 꺼내요.'}, {'term': '포맷 정렬', 'desc': ':5d는 5칸 우측정렬, :5.1f는 소수점1자리'}], quizQ: '리스트 안에 딕셔너리를 넣는 이유는?', quizOpts: ['속도', '여러 레코드 관리', '코드 줄이기', '메모리 절약'], quizAns: 1, quizExplain: '각 학생의 여러 정보를 딕셔너리로, 여러 학생을 리스트로 관리!'),
  const ExItem(no: 'G06', title: '중복 제거하기', category: 'G', categoryName: '리스트', difficulty: '기초', hardware: '화면', type: 'text', description: 'set()으로 리스트의 중복을 제거합니다.', pythonCode: "nums = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]\n\nprint(f'원본 ({len(nums)}개): {nums}')\n\nunique = list(set(nums))\nunique.sort()\nprint(f'중복제거 ({len(unique)}개): {unique}')\n\n# 순서 유지 중복 제거\nseen = []\nfor n in nums:\n    if n not in seen:\n        seen.append(n)\nprint(f'순서유지 ({len(seen)}개): {seen}')", expectedOutput: "원본 (11개): [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]\n중복제거 (7개): [1, 2, 3, 4, 5, 6, 9]\n순서유지 (7개): [3, 1, 4, 5, 9, 2, 6]", steps: ['set()으로 중복을 자동 제거합니다', '리스트로 다시 변환합니다', '순서를 유지하려면 직접 검사합니다'], concepts: [{'term': 'set()', 'desc': '중복을 허용하지 않는 집합 자료구조예요.'}, {'term': 'list(set(...))', 'desc': 'set으로 중복 제거 후 다시 리스트로 변환해요.'}, {'term': 'not in', 'desc': '리스트에 이미 있는지 확인하여 중복 방지해요.'}], quizQ: 'set([1,1,2,2,3])의 결과는?', quizOpts: ['[1,2,3]', '{1,2,3}', '[1,1,2,2,3]', '5'], quizAns: 1, quizExplain: 'set은 중복을 제거! {1,2,3}이 돼요.'),
  const ExItem(no: 'G07', title: '버블 정렬', category: 'G', categoryName: '리스트', difficulty: '고급', hardware: '화면', type: 'text', description: '가장 기본적인 정렬 알고리즘인 버블 정렬을 직접 구현합니다.', pythonCode: "nums = [64, 34, 25, 12, 22, 11, 90]\nprint(f'정렬 전: {nums}')\n\nn = len(nums)\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if nums[j] > nums[j + 1]:\n            nums[j], nums[j+1] = nums[j+1], nums[j]\n    print(f'{i+1}회차: {nums}')\n\nprint(f'정렬 후: {nums}')", expectedOutput: "정렬 전: [64, 34, 25, 12, 22, 11, 90]\n1회차: [34, 25, 12, 22, 11, 64, 90]\n2회차: [25, 12, 22, 11, 34, 64, 90]\n...\n정렬 후: [11, 12, 22, 25, 34, 64, 90]", steps: ['인접한 두 수를 비교합니다', '왼쪽이 크면 위치를 교환합니다', '한 바퀴 돌 때마다 가장 큰 수가 끝으로 이동합니다'], concepts: [{'term': '버블 정렬', 'desc': '인접한 두 요소를 비교-교환하며 큰 값을 뒤로 보내는 정렬이에요.'}, {'term': 'swap', 'desc': 'a, b = b, a로 두 변수의 값을 교환해요.'}, {'term': 'O(n²)', 'desc': '이중 반복이므로 데이터가 많으면 느려요.'}], quizQ: '버블 정렬에서 한 바퀴 후 확실한 것은?', quizOpts: ['전부 정렬됨', '가장 큰 수가 맨 뒤', '가장 작은 수가 맨 앞', '절반 정렬됨'], quizAns: 1, quizExplain: '한 바퀴 돌면 가장 큰 수가 끝으로 "떠올라" 가요!'),
  const ExItem(no: 'G08', title: '스택과 큐', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '리스트로 스택(LIFO)과 큐(FIFO)를 구현합니다.', pythonCode: "# 스택 (LIFO: 후입선출)\nstack = []\nstack.append('A')\nstack.append('B')\nstack.append('C')\nprint(f'스택: {stack}')\nprint(f'pop: {stack.pop()}')\nprint(f'pop: {stack.pop()}')\nprint(f'남은: {stack}')\n\nprint()\n\n# 큐 (FIFO: 선입선출)\nfrom collections import deque\nqueue = deque()\nqueue.append('1번')\nqueue.append('2번')\nqueue.append('3번')\nprint(f'큐: {list(queue)}')\nprint(f'처리: {queue.popleft()}')\nprint(f'처리: {queue.popleft()}')\nprint(f'남은: {list(queue)}')", expectedOutput: "스택: ['A', 'B', 'C']\npop: C\npop: B\n남은: ['A']\n\n큐: ['1번', '2번', '3번']\n처리: 1번\n처리: 2번\n남은: ['3번']", steps: ['스택: append로 넣고 pop으로 꺼냅니다', '큐: append로 넣고 popleft로 꺼냅니다', '스택은 마지막 것, 큐는 처음 것이 먼저 나옵니다'], concepts: [{'term': '스택 (LIFO)', 'desc': '마지막에 넣은 것이 먼저 나와요. 접시 쌓기처럼!'}, {'term': '큐 (FIFO)', 'desc': '먼저 넣은 것이 먼저 나와요. 줄 서기처럼!'}, {'term': 'deque', 'desc': '양쪽에서 넣고 뺄 수 있는 효율적인 자료구조예요.'}], quizQ: '스택에 1,2,3 넣고 pop하면?', quizOpts: ['1', '2', '3', '1,2,3'], quizAns: 2, quizExplain: '스택은 LIFO! 마지막에 넣은 3이 먼저 나와요.'),
  const ExItem(no: 'G09', title: '투표 집계 (빈도수)', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '딕셔너리로 투표 결과를 집계합니다.', pythonCode: "votes = ['민수','영희','민수','철수','영희','민수','영희','철수','민수']\n\ncount = {}\nfor v in votes:\n    count[v] = count.get(v, 0) + 1\n\nprint('=== 투표 결과 ===')\nfor name, cnt in sorted(count.items(), key=lambda x: -x[1]):\n    bar = '█' * cnt\n    print(f'{name}: {cnt}표 {bar}')\n\nwinner = max(count, key=count.get)\nprint(f'\\n당선: {winner} ({count[winner]}표)')", expectedOutput: "=== 투표 결과 ===\n민수: 4표 ████\n영희: 3표 ███\n철수: 2표 ██\n\n당선: 민수 (4표)", steps: ['각 이름의 등장 횟수를 셉니다', '득표순으로 정렬합니다', '가장 많은 표를 받은 사람이 당선'], concepts: [{'term': 'dict.get(key, 0)', 'desc': '키가 없으면 0을 반환하는 안전한 방법이에요.'}, {'term': 'max(dict, key=)', 'desc': '값 기준으로 가장 큰 키를 찾아요.'}, {'term': '빈도수 카운팅', 'desc': '각 항목이 몇 번 나오는지 세는 패턴이에요.'}], quizQ: "count.get('없는키', 0)의 결과는?", quizOpts: ['에러', 'None', '0', "'없는키'"], quizAns: 2, quizExplain: "키가 없으면 기본값 0을 반환해요!"),
  const ExItem(no: 'G10', title: '튜플과 언패킹', category: 'G', categoryName: '리스트', difficulty: '중급', hardware: '화면', type: 'text', description: '튜플의 특성과 언패킹 활용법을 배웁니다.', pythonCode: "# 튜플 기본\npoint = (3, 4)\nx, y = point  # 언패킹\nprint(f'좌표: ({x}, {y})')\n\n# 함수에서 여러 값 반환\ndef min_max(nums):\n    return min(nums), max(nums)\n\ndata = [5, 3, 8, 1, 9, 2]\nlo, hi = min_max(data)\nprint(f'최소: {lo}, 최대: {hi}')\n\n# swap\na, b = 10, 20\na, b = b, a\nprint(f'교환: a={a}, b={b}')", expectedOutput: "좌표: (3, 4)\n최소: 1, 최대: 9\n교환: a=20, b=10", steps: ['튜플로 여러 값을 묶습니다', '언패킹으로 각 변수에 분리합니다', '함수에서 여러 값을 반환할 때 유용합니다'], concepts: [{'term': '튜플', 'desc': '(1, 2, 3)처럼 수정 불가능한 리스트예요.'}, {'term': '언패킹', 'desc': 'x, y = (3, 4)처럼 튜플의 값을 변수에 풀어내요.'}, {'term': '다중 반환', 'desc': 'return a, b로 함수에서 여러 값을 반환해요.'}], quizQ: 'a, b = 1, 2 후 a와 b는?', quizOpts: ['a=1 b=2', 'a=2 b=1', 'a=(1,2)', '에러'], quizAns: 0, quizExplain: 'a에 1, b에 2가 각각 들어가요!'),

  // ═══════════════════════════════════════════
  //  H~J: 인터랙티브 (센서/카메라/게임)
  //  interactive_widgets.dart에서 렌더링
  // ═══════════════════════════════════════════
  const ExItem(no: 'H01', title: '흔들면 주사위 굴리기', category: 'H', categoryName: '센서', difficulty: '기초', hardware: '가속도', type: 'sensor', flutterWidget: 'dice', description: '스마트폰을 흔들면 랜덤 주사위가 굴려집니다!', pythonCode: "import random\ndef on_shake():\n    dice = random.randint(1, 6)\n    print(f'주사위: {dice}')", steps: ['가속도 센서가 활성화됩니다', '스마트폰을 세게 흔들어보세요', '1~6 랜덤 숫자가 나타납니다'], concepts: [{'term': '가속도 센서', 'desc': 'X,Y,Z 3방향 움직임을 측정해요.'}, {'term': 'randint(1,6)', 'desc': '1~6 랜덤 정수를 만들어요.'}, {'term': '이벤트 감지', 'desc': '합 > 20이면 흔든 것으로 판단.'}], quizQ: 'randint(1,6)의 범위는?', quizOpts: ['0~6', '1~6', '1~5', '0~5'], quizAns: 1, quizExplain: '양쪽 끝 포함! 1,2,3,4,5,6'),
  const ExItem(no: 'H02', title: '진동 모스부호 SOS', category: 'H', categoryName: '센서', difficulty: '기초', hardware: '진동', type: 'sensor', flutterWidget: 'sos', description: '진동 모터로 SOS 모스부호(···---···)를 보냅니다.', pythonCode: "def dot(): vibrate(200); sleep(200)\ndef dash(): vibrate(600); sleep(200)\n# S:··· O:--- S:···\ndot();dot();dot()\ndash();dash();dash()\ndot();dot();dot()", steps: ['SOS 버튼을 누릅니다', 'S(···): 짧은 진동 3번', 'O(---): 긴 진동 3번'], concepts: [{'term': '모스부호', 'desc': '짧은(·)과 긴(—) 신호 조합이에요.'}, {'term': '함수', 'desc': 'dot(),dash()로 반복 동작을 재사용해요.'}, {'term': 'vibrate(ms)', 'desc': '진동 시간을 밀리초로 지정해요.'}], quizQ: 'SOS를 모스부호로?', quizOpts: ['--- ··· ---', '··· --- ···', '··· ···', '--- ---'], quizAns: 1, quizExplain: 'S=···, O=---, 합치면 ··· --- ···!'),
  const ExItem(no: 'H03', title: '만보기', category: 'H', categoryName: '센서', difficulty: '중급', hardware: '가속도', type: 'sensor', flutterWidget: 'pedometer', description: '가속도 센서로 걸음 수를 세는 만보기입니다.', pythonCode: "steps = 0\ndef on_step():\n    global steps\n    steps += 1\n    print(f'걸음: {steps}')", steps: ['가속도 센서가 걸음을 감지합니다', '걸을 때마다 카운터가 증가합니다', '리셋 버튼으로 초기화할 수 있습니다'], concepts: [{'term': '만보기', 'desc': '가속도 변화 패턴으로 걸음을 감지해요.'}, {'term': '임계값', 'desc': '일정 세기 이상의 움직임만 걸음으로 인정해요.'}, {'term': '카운터', 'desc': '감지할 때마다 1씩 증가하는 변수예요.'}], quizQ: '만보기는 어떤 센서를 사용?', quizOpts: ['GPS', '가속도', '카메라', '자이로'], quizAns: 1, quizExplain: '가속도 센서의 변화 패턴으로 걸음을 감지해요!'),
  const ExItem(no: 'H04', title: '수평계', category: 'H', categoryName: '센서', difficulty: '중급', hardware: '가속도', type: 'sensor', flutterWidget: 'level', description: '스마트폰의 기울기를 측정하는 수평계입니다.', pythonCode: "accel = get_accelerometer()\nx_angle = accel.x\ny_angle = accel.y\nprint(f'기울기: X={x_angle:.1f} Y={y_angle:.1f}')", steps: ['스마트폰을 평평한 곳에 놓으세요', '기울이면 버블이 움직입니다', '중앙에 오면 수평입니다'], concepts: [{'term': '수평계', 'desc': '기울기를 측정하여 수평인지 확인하는 도구예요.'}, {'term': 'X/Y 기울기', 'desc': 'X는 좌우, Y는 앞뒤 기울기를 나타내요.'}, {'term': '중력 가속도', 'desc': '9.8m/s²의 중력을 기준으로 기울기를 계산해요.'}], quizQ: '수평일 때 X,Y 값은?', quizOpts: ['0, 0', '9.8, 9.8', '1, 1', '-1, -1'], quizAns: 0, quizExplain: '완전히 수평이면 X=0, Y=0에 가까워요!'),
  const ExItem(no: 'H05', title: '흔들어서 색상 바꾸기', category: 'H', categoryName: '센서', difficulty: '기초', hardware: '가속도', type: 'sensor', flutterWidget: 'shakeColor', description: '스마트폰을 흔들 때마다 화면 색상이 랜덤으로 바뀝니다.', pythonCode: "import random\ndef on_shake():\n    r = random.randint(0, 255)\n    g = random.randint(0, 255)\n    b = random.randint(0, 255)\n    set_bg_color(r, g, b)", steps: ['스마트폰을 흔들어보세요', '배경 색상이 랜덤으로 바뀝니다', 'RGB 색상 코드가 표시됩니다'], concepts: [{'term': 'RGB', 'desc': '빨강(R), 초록(G), 파랑(B)의 조합으로 모든 색을 만들어요.'}, {'term': '0~255', 'desc': '각 색상 채널은 0(없음)~255(최대) 범위예요.'}, {'term': '랜덤 색상', 'desc': 'R,G,B 각각 랜덤 값을 생성하면 랜덤 색상이 돼요.'}], quizQ: 'RGB(255,0,0)은 무슨 색?', quizOpts: ['파랑', '초록', '빨강', '흰색'], quizAns: 2, quizExplain: 'R=255(최대), G=0, B=0이면 순수 빨간색!'),
  const ExItem(no: 'H06', title: '기울기 방향 표시기', category: 'H', categoryName: '센서', difficulty: '기초', hardware: '가속도', type: 'sensor', flutterWidget: 'tiltArrow', description: '스마트폰 기울기 방향을 화살표로 표시합니다.', pythonCode: "accel = get_accelerometer()\nif abs(accel.x) > abs(accel.y):\n    direction = '← 왼쪽' if accel.x > 0 else '오른쪽 →'\nelse:\n    direction = '↑ 위' if accel.y < 0 else '아래 ↓'", steps: ['스마트폰을 기울여보세요', '기울기 방향에 따라 화살표가 바뀝니다', '각도 값도 함께 표시됩니다'], concepts: [{'term': '방향 감지', 'desc': 'X와 Y 가속도의 크기와 부호로 방향을 판단해요.'}, {'term': 'abs()', 'desc': '절대값으로 크기만 비교할 때 사용해요.'}, {'term': '4방향', 'desc': '상하좌우 중 가장 크게 기울어진 방향을 표시해요.'}], quizQ: 'abs(-5)의 결과는?', quizOpts: ['-5', '5', '0', '에러'], quizAns: 1, quizExplain: 'abs()는 절대값! 부호를 제거하여 5가 돼요.'),
  const ExItem(no: 'H07', title: '진동 패턴 만들기', category: 'H', categoryName: '센서', difficulty: '중급', hardware: '진동', type: 'sensor', flutterWidget: 'vibePattern', description: '짧은 진동과 긴 진동을 조합하여 나만의 패턴을 만듭니다.', pythonCode: "pattern = [200, 100, 200, 100, 500]\n# 200ms 진동, 100ms 대기, 200ms 진동...\nvibrate_pattern(pattern)", steps: ['짧은/긴 진동 버튼으로 패턴을 구성합니다', '재생 버튼으로 패턴을 실행합니다', '초기화하여 새 패턴을 만들 수 있습니다'], concepts: [{'term': '진동 패턴', 'desc': '진동과 대기 시간의 배열로 리듬을 만들어요.'}, {'term': '밀리초(ms)', 'desc': '1000ms = 1초. 200ms는 0.2초예요.'}, {'term': '배열', 'desc': '[200, 100, 500]처럼 값들의 순서 있는 목록이에요.'}], quizQ: '500ms는 몇 초?', quizOpts: ['0.05초', '0.5초', '5초', '50초'], quizAns: 1, quizExplain: '1000ms = 1초이므로 500ms = 0.5초!'),
  const ExItem(no: 'H08', title: '흔들기 카운터', category: 'H', categoryName: '센서', difficulty: '기초', hardware: '가속도', type: 'sensor', flutterWidget: 'shakeCount', description: '스마트폰을 흔든 횟수를 세는 카운터입니다.', pythonCode: "count = 0\ndef on_shake():\n    global count\n    count += 1\n    print(f'흔들기: {count}회')", steps: ['스마트폰을 흔들어보세요', '흔들 때마다 카운터가 올라갑니다', '리셋 버튼으로 초기화할 수 있습니다'], concepts: [{'term': 'global', 'desc': '함수 안에서 바깥 변수를 수정할 때 사용해요.'}, {'term': '카운터', 'desc': '이벤트 발생 시마다 1씩 증가하는 변수예요.'}, {'term': '임계값', 'desc': '일정 세기 이상의 흔들림만 감지해요.'}], quizQ: 'count += 1은 무슨 뜻?', quizOpts: ['count = 1', 'count에 1 더하기', 'count - 1', '에러'], quizAns: 1, quizExplain: 'count += 1은 count = count + 1과 같아요!'),
  const ExItem(no: 'H09', title: '기울기 슬라이더', category: 'H', categoryName: '센서', difficulty: '중급', hardware: '가속도', type: 'sensor', flutterWidget: 'tiltSlider', description: '스마트폰 기울기로 슬라이더 값을 제어합니다.', pythonCode: "accel = get_accelerometer()\nvalue = map(accel.x, -10, 10, 0, 100)\nprint(f'값: {value:.0f}%')", steps: ['스마트폰을 좌우로 기울여보세요', '기울기에 따라 슬라이더가 움직입니다', '0~100% 범위로 값이 표시됩니다'], concepts: [{'term': 'map()', 'desc': '한 범위의 값을 다른 범위로 변환해요.'}, {'term': '기울기 → 값', 'desc': '물리적 기울기를 디지털 값으로 변환해요.'}, {'term': 'clamp', 'desc': '값을 최소~최대 범위로 제한해요.'}], quizQ: '센서값 -10~10을 0~100으로 바꾸면 0은?', quizOpts: ['0', '50', '100', '-50'], quizAns: 1, quizExplain: '-10→0, 0→50, 10→100으로 매핑! 중간값 0은 50이 돼요.'),
  const ExItem(no: 'H10', title: '움직임 감지 알람', category: 'H', categoryName: '센서', difficulty: '중급', hardware: '가속도', type: 'sensor', flutterWidget: 'motionAlarm', description: '스마트폰이 움직이면 알람이 울리는 보안 시스템입니다.', pythonCode: "armed = True\ndef on_motion(accel):\n    if armed and accel.total > 12:\n        print('움직임 감지!')\n        vibrate(1000)\n        play_alarm()", steps: ['활성화 버튼으로 알람을 켭니다', '스마트폰을 움직이지 않고 내려놓으세요', '움직임이 감지되면 경고가 울립니다'], concepts: [{'term': '모션 감지', 'desc': '가속도 변화를 감지하여 움직임을 알아차려요.'}, {'term': '임계값', 'desc': '일정 수준 이상의 움직임만 감지하여 오작동을 방지해요.'}, {'term': '상태 관리', 'desc': 'armed 변수로 알람 활성화/비활성화를 관리해요.'}], quizQ: '보안 알람은 어떤 센서?', quizOpts: ['GPS', '카메라', '가속도', '마이크'], quizAns: 2, quizExplain: '가속도 센서로 물리적 움직임을 감지해요!'),

  // ── I. 카메라/소리 ──
  const ExItem(no: 'I01', title: '카메라로 사진 찍기', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '카메라', type: 'camera', flutterWidget: 'camera', description: '스마트폰 카메라로 사진을 찍어봅시다!', pythonCode: "cam = Camera()\nphoto = cam.capture()\nshow_image(photo)", steps: ['촬영 버튼을 누릅니다', '사진을 찍으면 화면에 표시됩니다', '파일 크기가 표시됩니다'], concepts: [{'term': '카메라 API', 'desc': '코드로 카메라를 열고 촬영할 수 있어요.'}, {'term': '권한', 'desc': '카메라 사용 시 허락이 필요해요.'}, {'term': 'JPEG', 'desc': '사진 파일 형식이에요.'}], quizQ: '카메라 허용이 필요한 이유?', quizOpts: ['배터리', '개인정보', '인터넷', '화면'], quizAns: 1, quizExplain: '카메라는 개인정보와 관련! 허용 필요.'),
  const ExItem(no: 'I02', title: '손전등 켜기/끄기', category: 'I', categoryName: '카메라/소리', difficulty: '기초', hardware: '플래시', type: 'sensor', flutterWidget: 'flashlight', description: '스마트폰 카메라 플래시를 손전등으로 사용합니다.', pythonCode: "flash = Flashlight()\nflash.on()\nprint('손전등 켜짐!')\nflash.off()\nprint('손전등 꺼짐!')", steps: ['버튼을 누르면 플래시가 켜집니다', '다시 누르면 꺼집니다', '토글 방식으로 작동합니다'], concepts: [{'term': '토글', 'desc': '누를 때마다 켜짐/꺼짐이 번갈아 바뀌어요.'}, {'term': '플래시 LED', 'desc': '카메라 옆의 밝은 LED를 제어해요.'}, {'term': 'boolean', 'desc': 'True/False로 켜짐/꺼짐 상태를 저장해요.'}], quizQ: '토글이란?', quizOpts: ['항상 켜기', '항상 끄기', '켜짐↔꺼짐 전환', '삭제'], quizAns: 2, quizExplain: '토글은 누를 때마다 상태가 반대로 바뀌는 것!'),
  const ExItem(no: 'I03', title: '셀카 찍기', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '전면 카메라', type: 'camera', flutterWidget: 'selfie', description: '전면 카메라로 셀카를 찍어봅시다!', pythonCode: "cam = Camera(front=True)\nphoto = cam.capture()\nshow_image(photo)", steps: ['셀카 버튼을 누릅니다', '전면 카메라가 열립니다', '촬영 후 사진이 표시됩니다'], concepts: [{'term': '전면 카메라', 'desc': '화면 쪽에 있는 셀카용 카메라예요.'}, {'term': 'front=True', 'desc': '전면 카메라를 사용하라는 옵션이에요.'}, {'term': '미러링', 'desc': '셀카는 좌우가 반전되어 보여요.'}], quizQ: '전면 카메라는 주로 어디에?', quizOpts: ['뒤', '옆', '화면 위', '아래'], quizAns: 2, quizExplain: '전면 카메라는 화면 위쪽에 있어서 셀카를 찍을 수 있어요!'),
  const ExItem(no: 'I04', title: '갤러리에서 사진 선택', category: 'I', categoryName: '카메라/소리', difficulty: '기초', hardware: '갤러리', type: 'camera', flutterWidget: 'gallery', description: '스마트폰 갤러리에서 사진을 선택합니다.', pythonCode: "photo = Gallery.pick()\nshow_image(photo)\nprint(f'크기: {photo.size}KB')", steps: ['갤러리 버튼을 누릅니다', '사진을 선택합니다', '선택한 사진이 표시됩니다'], concepts: [{'term': '갤러리', 'desc': '스마트폰에 저장된 사진을 보는 앱이에요.'}, {'term': 'ImageSource.gallery', 'desc': '카메라 대신 갤러리에서 사진을 가져와요.'}, {'term': '파일 선택', 'desc': '사용자가 원하는 사진을 직접 고를 수 있어요.'}], quizQ: '갤러리와 카메라의 차이는?', quizOpts: ['없음', '갤러리=저장된 사진, 카메라=새 촬영', '같은 것', '갤러리=동영상'], quizAns: 1, quizExplain: '갤러리는 이미 찍은 사진, 카메라는 새로 찍는 것!'),
  const ExItem(no: 'I05', title: '타이머 카메라', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '카메라', type: 'camera', flutterWidget: 'timerCam', description: '3초 카운트다운 후 자동으로 사진을 촬영합니다.', pythonCode: "for i in range(3, 0, -1):\n    print(f'{i}...')\n    sleep(1000)\nphoto = Camera().capture()\nprint('찰칵!')", steps: ['촬영 버튼을 누릅니다', '3, 2, 1 카운트다운이 시작됩니다', '0이 되면 자동으로 촬영됩니다'], concepts: [{'term': '카운트다운', 'desc': 'range(3,0,-1)로 3,2,1 역순 반복해요.'}, {'term': '딜레이', 'desc': 'sleep(1000)으로 1초씩 대기해요.'}, {'term': '자동 촬영', 'desc': '타이머 완료 후 코드가 자동으로 카메라를 작동시켜요.'}], quizQ: 'range(3,0,-1)이 만드는 숫자는?', quizOpts: ['0,1,2,3', '3,2,1', '3,2,1,0', '1,2,3'], quizAns: 1, quizExplain: '3부터 1까지 역순! 0은 포함 안 돼요.'),
  const ExItem(no: 'I06', title: '연속 촬영', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '카메라', type: 'camera', flutterWidget: 'burstCam', description: '버튼 한 번으로 3장을 연속 촬영합니다.', pythonCode: "photos = []\nfor i in range(3):\n    photo = Camera().capture()\n    photos.append(photo)\n    print(f'{i+1}장 촬영!')", steps: ['연속촬영 버튼을 누릅니다', '3장이 빠르게 촬영됩니다', '촬영된 사진들이 나란히 표시됩니다'], concepts: [{'term': '연속 촬영', 'desc': '짧은 간격으로 여러 장을 연속으로 찍어요.'}, {'term': '리스트 저장', 'desc': '촬영된 사진들을 리스트에 모아요.'}, {'term': '반복 촬영', 'desc': 'for문으로 지정한 횟수만큼 반복 촬영해요.'}], quizQ: '3장 연속촬영에 필요한 반복 횟수?', quizOpts: ['1', '2', '3', '4'], quizAns: 2, quizExplain: 'range(3)으로 3번 반복하면 3장 촬영!'),
  const ExItem(no: 'I07', title: '사진 필터 효과', category: 'I', categoryName: '카메라/소리', difficulty: '고급', hardware: '카메라', type: 'camera', flutterWidget: 'photoFilter', description: '촬영한 사진에 흑백, 세피아, 반전 필터를 적용합니다.', pythonCode: "photo = Camera().capture()\ngray = apply_filter(photo, 'grayscale')\nsepia = apply_filter(photo, 'sepia')\ninvert = apply_filter(photo, 'invert')", steps: ['사진을 촬영합니다', '필터 버튼으로 효과를 선택합니다', '원본과 필터 적용 사진을 비교합니다'], concepts: [{'term': '컬러 필터', 'desc': '색상 값을 수학적으로 변환하여 효과를 만들어요.'}, {'term': '그레이스케일', 'desc': 'R,G,B를 평균내어 흑백으로 만들어요.'}, {'term': '색상 반전', 'desc': '각 색상을 255에서 빼면 반전 효과가 나와요.'}], quizQ: '흑백 변환 공식은?', quizOpts: ['R+G+B', '(R+G+B)/3', 'R*G*B', 'R-G-B'], quizAns: 1, quizExplain: 'RGB 평균값으로 밝기를 계산하면 흑백이 돼요!'),
  const ExItem(no: 'I08', title: 'QR코드 표시하기', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '화면', type: 'canvas', flutterWidget: 'qrDisplay', description: '텍스트를 입력하면 QR코드 패턴을 생성합니다.', pythonCode: "text = 'Hello Python!'\nqr = QR.generate(text)\nshow_image(qr)", steps: ['텍스트를 입력합니다', 'QR코드 패턴이 생성됩니다', '스캔하여 내용을 확인할 수 있습니다'], concepts: [{'term': 'QR코드', 'desc': '정보를 흑백 패턴으로 인코딩한 2차원 바코드예요.'}, {'term': '인코딩', 'desc': '텍스트를 특정 규칙으로 변환하는 과정이에요.'}, {'term': '2차원 배열', 'desc': 'QR코드는 행과 열로 이루어진 격자 패턴이에요.'}], quizQ: 'QR코드에 담을 수 있는 것은?', quizOpts: ['텍스트만', 'URL만', '텍스트,URL,숫자 등', '사진'], quizAns: 2, quizExplain: 'QR코드는 텍스트, URL, 숫자 등 다양한 데이터를 담을 수 있어요!'),
  const ExItem(no: 'I09', title: '색상 선택기', category: 'I', categoryName: '카메라/소리', difficulty: '중급', hardware: '화면', type: 'canvas', flutterWidget: 'colorPicker', description: 'HSV 색상 휠에서 원하는 색상을 선택합니다.', pythonCode: "h, s, v = 180, 100, 100\ncolor = hsv_to_rgb(h, s, v)\nprint(f'RGB: {color}')", steps: ['색상 휠에서 색을 터치합니다', '선택한 색상의 RGB 값이 표시됩니다', '밝기를 조절할 수 있습니다'], concepts: [{'term': 'HSV', 'desc': '색상(Hue), 채도(Saturation), 명도(Value)로 색을 표현해요.'}, {'term': '색상 휠', 'desc': '360도 원형으로 모든 색상을 배치한 것이에요.'}, {'term': 'RGB 변환', 'desc': 'HSV 값을 RGB로 변환하여 화면에 표시해요.'}], quizQ: 'HSV에서 H는?', quizOpts: ['밝기', '색상', '채도', '투명도'], quizAns: 1, quizExplain: 'H=Hue(색상), S=Saturation(채도), V=Value(명도)!'),
  const ExItem(no: 'I10', title: '디지털 시계', category: 'I', categoryName: '카메라/소리', difficulty: '기초', hardware: '화면', type: 'canvas', flutterWidget: 'digitalClock', description: '실시간으로 업데이트되는 디지털 시계입니다.', pythonCode: "while True:\n    now = datetime.now()\n    print(f'{now.hour:02d}:{now.minute:02d}:{now.second:02d}')\n    sleep(1000)", steps: ['시계가 자동으로 시작됩니다', '1초마다 시간이 업데이트됩니다', '현재 날짜도 함께 표시됩니다'], concepts: [{'term': '실시간 업데이트', 'desc': 'Timer로 1초마다 화면을 갱신해요.'}, {'term': ':02d', 'desc': '숫자를 2자리로 표시해요. 9 → 09'}, {'term': 'datetime', 'desc': '현재 날짜와 시간을 가져오는 모듈이에요.'}], quizQ: ':02d 포맷으로 5를 표시하면?', quizOpts: ['5', '05', '50', '005'], quizAns: 1, quizExplain: ':02d는 2자리로 맞추고 빈 자리를 0으로 채워요!'),

  // ── J. 게임/그래픽 ──
  const ExItem(no: 'J01', title: '기울기로 공 굴리기', category: 'J', categoryName: '게임', difficulty: '중급', hardware: '가속도', type: 'sensor', flutterWidget: 'ball', description: '스마트폰을 기울여 공을 움직이고 목표물을 잡으세요!', pythonCode: "ball_x += -accel.x * 1.5\nball_y += accel.y * 1.5\nif distance(ball, target) < 22:\n    score += 1", steps: ['스마트폰을 평평하게 들어주세요', '기울이면 빨간 공이 움직입니다', '노란 목표물에 닿으면 점수 UP!'], concepts: [{'term': '가속도 → 속도', 'desc': '센서값을 공의 이동 속도로 변환해요.'}, {'term': 'clamp', 'desc': '공이 화면 밖으로 안 나가게 범위를 제한해요.'}, {'term': '충돌 감지', 'desc': '두 점 사이 거리가 가까우면 충돌!'}], quizQ: '공이 화면 밖으로 안 나가게 하는 기법?', quizOpts: ['stop', 'clamp', 'break', 'return'], quizAns: 1, quizExplain: 'clamp(값, 최소, 최대)로 범위를 제한해요!'),
  const ExItem(no: 'J02', title: '반응속도 테스트', category: 'J', categoryName: '게임', difficulty: '기초', hardware: '터치', type: 'canvas', flutterWidget: 'reactionTest', description: '화면이 초록색으로 바뀌면 최대한 빨리 터치하세요!', pythonCode: "import time\nwait_random()\nstart = time.time()\n# 사용자 터치 대기\nreaction = (time.time() - start) * 1000\nprint(f'{reaction:.0f}ms')", steps: ['시작 버튼을 누릅니다', '빨간색이 초록색으로 바뀔 때까지 기다립니다', '초록색이 되면 최대한 빨리 터치!'], concepts: [{'term': '반응 시간', 'desc': '자극을 보고 행동하기까지 걸리는 시간이에요.'}, {'term': 'time.time()', 'desc': '현재 시각을 초 단위로 반환해요.'}, {'term': '밀리초(ms)', 'desc': '1초 = 1000ms. 보통 반응 시간은 200~400ms.'}], quizQ: '평균 반응 시간은 약?', quizOpts: ['10ms', '50ms', '250ms', '1000ms'], quizAns: 2, quizExplain: '사람의 평균 반응 시간은 약 250ms(0.25초)!'),
  const ExItem(no: 'J03', title: '두더지 잡기', category: 'J', categoryName: '게임', difficulty: '중급', hardware: '터치', type: 'canvas', flutterWidget: 'whackMole', description: '랜덤으로 나타나는 두더지를 빨리 잡으세요!', pythonCode: "score = 0\ndef show_mole():\n    pos = random.choice(holes)\n    show_at(pos)\n\ndef on_tap(pos):\n    if pos == mole_pos:\n        score += 1", steps: ['두더지가 랜덤 위치에 나타납니다', '두더지를 탭하면 점수가 올라갑니다', '놓치면 다른 곳에 새로 나타납니다'], concepts: [{'term': '랜덤 위치', 'desc': '무작위 격자 위치에 두더지가 나타나요.'}, {'term': '터치 감지', 'desc': '화면 터치 위치와 두더지 위치를 비교해요.'}, {'term': '타이머', 'desc': '일정 시간마다 두더지 위치를 바꿔요.'}], quizQ: '게임에서 점수를 올리려면?', quizOpts: ['기다린다', '두더지를 탭한다', '흔든다', '기울인다'], quizAns: 1, quizExplain: '두더지가 나타난 곳을 빨리 탭하면 점수가 올라가요!'),
  const ExItem(no: 'J04', title: '기억력 게임', category: 'J', categoryName: '게임', difficulty: '고급', hardware: '터치', type: 'canvas', flutterWidget: 'simonSays', description: '색상 순서를 기억하고 따라하는 사이먼 게임입니다.', pythonCode: "sequence = []\ndef add_color():\n    sequence.append(random.choice(['R','G','B','Y']))\n    show_sequence()\n\ndef on_tap(color):\n    if color == sequence[current]:\n        next()", steps: ['시작하면 색상 하나가 빛납니다', '같은 순서로 터치합니다', '매 라운드 하나씩 색상이 추가됩니다'], concepts: [{'term': '시퀀스', 'desc': '색상이 보여지는 순서를 기억해야 해요.'}, {'term': '패턴 매칭', 'desc': '사용자 입력과 정답 순서를 하나씩 비교해요.'}, {'term': '난이도 증가', 'desc': '라운드가 올라갈수록 외울 색상이 늘어나요.'}], quizQ: '사이먼 게임에서 중요한 능력은?', quizOpts: ['계산 능력', '기억력', '체력', '타이핑'], quizAns: 1, quizExplain: '색상 순서를 기억하는 기억력 게임이에요!'),
  const ExItem(no: 'J05', title: '틱택토 (삼목)', category: 'J', categoryName: '게임', difficulty: '중급', hardware: '터치', type: 'canvas', flutterWidget: 'ticTacToe', description: 'O와 X를 번갈아 놓아 3개를 먼저 완성하면 승리!', pythonCode: "board = [['']*3 for _ in range(3)]\ndef check_win(mark):\n    # 가로, 세로, 대각선 검사\n    for row in board:\n        if all(c == mark for c in row):\n            return True", steps: ['3x3 격자에 번갈아 O/X를 놓습니다', '가로, 세로, 대각선으로 3개를 먼저 완성하면 승리', '모든 칸이 차면 무승부'], concepts: [{'term': '2차원 배열', 'desc': '3x3 격자를 리스트의 리스트로 표현해요.'}, {'term': '승리 조건', 'desc': '가로/세로/대각선 중 하나가 같은 표시로 채워지면 승리!'}, {'term': '턴 교대', 'desc': 'O와 X가 번갈아가며 놓는 방식이에요.'}], quizQ: '틱택토에서 이기려면?', quizOpts: ['5개 연속', '4개 연속', '3개 연속', '2개 연속'], quizAns: 2, quizExplain: '3x3 격자에서 3개를 일렬로 먼저 완성하면 승리!'),
  const ExItem(no: 'J06', title: '숫자 퍼즐 (15퍼즐)', category: 'J', categoryName: '게임', difficulty: '고급', hardware: '터치', type: 'canvas', flutterWidget: 'slidePuzzle', description: '1~15 숫자를 순서대로 맞추는 슬라이딩 퍼즐입니다.', pythonCode: "board = shuffle(range(1, 16) + [0])\ndef slide(pos):\n    if is_adjacent(pos, empty):\n        swap(pos, empty)", steps: ['숫자 타일이 섞여있습니다', '빈 칸 옆의 타일을 탭하면 이동합니다', '1~15 순서로 맞추면 완성!'], concepts: [{'term': '슬라이딩 퍼즐', 'desc': '빈 칸을 이용해 타일을 밀어 정렬하는 퍼즐이에요.'}, {'term': '인접 검사', 'desc': '빈 칸의 상하좌우만 이동 가능해요.'}, {'term': '셔플', 'desc': '랜덤으로 섞어서 퍼즐을 시작해요.'}], quizQ: '15퍼즐의 타일 개수는?', quizOpts: ['14개', '15개', '16개', '9개'], quizAns: 1, quizExplain: '1~15 숫자 타일 15개 + 빈 칸 1개 = 총 16칸!'),
  const ExItem(no: 'J07', title: '스네이크 게임', category: 'J', categoryName: '게임', difficulty: '고급', hardware: '스와이프', type: 'canvas', flutterWidget: 'snake', description: '뱀을 조종해서 먹이를 먹고 점점 길어지는 게임입니다.', pythonCode: "snake = [(5,5)]\ndir = (1, 0)  # 오른쪽\n\ndef update():\n    head = (snake[0][0]+dir[0], snake[0][1]+dir[1])\n    snake.insert(0, head)\n    if head == food:\n        score += 1\n    else:\n        snake.pop()", steps: ['스와이프로 뱀의 방향을 조종합니다', '먹이를 먹으면 뱀이 길어집니다', '벽이나 자기 몸에 부딪히면 게임 오버!'], concepts: [{'term': '스네이크', 'desc': '머리가 이동하고 꼬리가 따라오는 방식이에요.'}, {'term': '리스트 조작', 'desc': 'insert(0)로 머리 추가, pop()으로 꼬리 제거해요.'}, {'term': '충돌 감지', 'desc': '머리가 벽이나 몸과 겹치면 게임 오버!'}], quizQ: '뱀이 먹이를 먹으면?', quizOpts: ['짧아진다', '길어진다', '사라진다', '멈춘다'], quizAns: 1, quizExplain: '먹이를 먹으면 꼬리가 늘어나 뱀이 길어져요!'),
  const ExItem(no: 'J08', title: '타이핑 게임', category: 'J', categoryName: '게임', difficulty: '중급', hardware: '키보드', type: 'canvas', flutterWidget: 'typingGame', description: '떨어지는 단어를 빨리 입력하여 없애는 게임입니다.', pythonCode: "words = ['python', 'code', 'game']\nfor word in falling_words:\n    if input_text == word:\n        score += 1\n        remove(word)", steps: ['단어가 위에서 아래로 떨어집니다', '단어를 빠르게 입력합니다', '맞으면 점수 획득, 바닥에 닿으면 게임 오버!'], concepts: [{'term': '타이핑 속도', 'desc': '얼마나 빠르게 정확하게 타이핑하는지 측정해요.'}, {'term': '문자열 비교', 'desc': '입력한 텍스트와 떨어지는 단어를 비교해요.'}, {'term': '애니메이션', 'desc': '단어가 아래로 이동하는 효과를 타이머로 구현해요.'}], quizQ: '타이핑 게임에서 점수를 올리려면?', quizOpts: ['기다린다', '빠르게 입력', '화면을 탭', '흔든다'], quizAns: 1, quizExplain: '떨어지는 단어를 빠르고 정확하게 입력하면 점수가 올라가요!'),
  const ExItem(no: 'J09', title: '그림 그리기', category: 'J', categoryName: '게임', difficulty: '기초', hardware: '터치', type: 'canvas', flutterWidget: 'drawing', description: '손가락으로 화면에 자유롭게 그림을 그립니다.', pythonCode: "canvas = Canvas()\ndef on_touch_move(x, y):\n    canvas.draw_point(x, y, color, size)", steps: ['화면을 터치하며 그림을 그립니다', '색상과 굵기를 선택할 수 있습니다', '지우기 버튼으로 초기화합니다'], concepts: [{'term': '터치 이벤트', 'desc': '손가락이 움직일 때마다 좌표를 받아요.'}, {'term': 'Canvas', 'desc': '그림을 그릴 수 있는 도화지예요.'}, {'term': '경로 기록', 'desc': '터치 좌표를 리스트에 저장하여 선을 그려요.'}], quizQ: '그림을 그리려면 어떤 이벤트?', quizOpts: ['클릭', '터치 드래그', '흔들기', '기울이기'], quizAns: 1, quizExplain: '손가락을 터치한 채로 움직이면(드래그) 그림이 그려져요!'),
  const ExItem(no: 'J10', title: '기울기 미로 탈출', category: 'J', categoryName: '게임', difficulty: '고급', hardware: '가속도', type: 'sensor', flutterWidget: 'maze', description: '스마트폰을 기울여 공을 움직이고 미로를 탈출하세요!', pythonCode: "ball_x += -accel.x * 1.5\nball_y += accel.y * 1.5\nif hit_wall(ball, walls):\n    bounce_back(ball)\nif ball == exit_pos:\n    print('탈출 성공!')", steps: ['스마트폰을 기울여 공을 움직입니다', '벽에 부딪히면 공이 멈춥니다', '출구(초록)에 도달하면 클리어!'], concepts: [{'term': '미로', 'desc': '벽으로 둘러싸인 경로를 찾아 탈출하는 퍼즐이에요.'}, {'term': '벽 충돌', 'desc': '공이 벽에 닿으면 더 이상 이동할 수 없어요.'}, {'term': '경로 찾기', 'desc': '벽을 피해 출구까지의 길을 찾아야 해요.'}], quizQ: '미로 게임에서 조종 방법은?', quizOpts: ['터치', '스와이프', '기울이기', '음성'], quizAns: 2, quizExplain: '가속도 센서를 이용해 스마트폰 기울기로 공을 조종해요!'),
];
